### PR TITLE
Dispatch semaphores on Darwin (#2351)

### LINKED ISSUE #2351: Semaphores in sandboxed Mac app
I was debugging the same problem of PJMEDIA event manager not starting in recent PJSIP version in a sandboxed Mac app as reported in #2331. With the same error “Error creating PJMEDIA event manager: Operation not permitted [status=120001]”.

The last version that works is 2.7.2. It was “broken” by f61de805c8ef2af6d450c701f06902143e26369c, specifically by adding the event manager creation to `pjsip/src/pjsua-lib/pjsua_media.c`.

I discovered that the problem is in POSIX semaphores. They [don’t work](https://developer.apple.com/library/archive/documentation/Security/Conceptual/AppSandboxDesignGuide/AppSandboxInDepth/AppSandboxInDepth.html#//apple_ref/doc/uid/TP40011183-CH3-SW24) in a sandboxed Mac app by default. To make them work, apparently one has to create a so-called app group. App groups are normally used to share data between apps of the same developer. And POSIX semaphores work in a sandboxed environment only when their names are composed in a special way containing app group names. Also, there is a limit of 31 bytes for the semaphore name, which puts additional restriction to the app group name.

I think semaphores never worked in sandboxed Mac apps. The problem wasn’t coming up only by coincidence, probably because no semaphore code was running in a typical PJSUA API usage. I’ve been using it for years without encountering this problem!

One possible solution to this is to make the app developer create an artificial app group and to make this name configurable in PJSIP.

Another solution would be to use semaphores from the dispatch library (`dispatch_semaphore_create(3)`). This is a newer Apple’s approach to multitasking. I’ve already implemented it in PJSIP and can share results, if you’re interested.

### PR DESCRIPTION
**Pull request by eofster**
Dispatch semaphore is a more modern semaphore implementation on Apple platforms. Apple claims it is more efficient. A call down to kernel is only needed when the calling thread needs to be blocked.

Dispatch semaphores work in sandboxed Mac apps, but POSIX semaphores don’t.

Closes #2351

### CODE REVIEW

**Comment by eofster** [comment]
Are there any tests to run that touch semaphore code? For example, I don’t think `pj_sem_trywait()` has ever been called in my manual testing by running the app using the PJSUA API.

**Comment by sauwming** [comment]
For reference, here's Apple's doc regarding [dispatch_semaphore](https://developer.apple.com/documentation/dispatch/dispatch_semaphore_t?language=objc).

I tested here on Mac OS and iOS and it worked fine.

There's pjlib-test for semaphore, albeit a very simple one, i.e. only trying to call the semaphore APIs (including `trywait`) and checking the return value.

File: pjlib/include/pj/config.h [hunk 1]
```diff
@@ -804,6 +804,19 @@
 #  define PJ_HAS_SEMAPHORE	    1
 #endif
 
+/**
+ * Use dispatch semaphores on Darwin.
+ *
+ * Default: 1 on Darwin, 0 otherwise
+ */
+#ifndef PJ_SEMAPHORE_USE_DISPATCH_SEM
+#   if defined(PJ_DARWINOS)
```
Comment (nanangizz) [inline pjlib/include/pj/config.h:813]: a minor, for safety and consistency, please update to `#if defined(PJ_DARWINOS) && PJ_DARWINOS!=0`
