### PR TITLE
Don't terminate call on failed SDP negotiation during EARLY state

### LINKED ISSUE #3135: Wrong order of replies to UPDATE request with unacceptable SDP offer
### Describe the bug

pjsip is UAS and receiving UPDATE request before finishing original INVITE transaction. If SDP negotiation for this UPDATE is failed, pjsip first terminates INVITE transaction and then sends reply 488 "Not acceptable" for the UPDATE.
During `inv_negotiate_sdp()` there is execution of callback `pjsua_call_on_media_update` which can terminate the dialog. So if SDP negotiation failed, pjsua first sends reply to original INVITE, terminating current dialog (415 "Unsupported Media Type"), and only after that it is sending reply 488/UPDATE. I think, that correct behavior must be opposite, 488/UPDATE followed by 415/INVITE.

### Steps to reproduce

Scripts to reproduce the issue are attached
[uac-upd-sdp-decline_xml.txt](https://github.com/pjsip/pjproject/files/8812373/uac-upd-sdp-decline_xml.txt)
[uac-upd-sdp-decline_py.txt](https://github.com/pjsip/pjproject/files/8812374/uac-upd-sdp-decline_py.txt)

### PJSIP version

master

### Context

$ mv uac-upd-sdp-decline_xml.txt ./pjproject/tests/pjsua/scripts-sipp/uac-upd-sdp-decline.xml
$ mv uac-upd-sdp-decline_py.txt ./pjproject/tests/pjsua/scripts-sipp/uac-upd-sdp-decline.py
$ cd pjproject/tests/pjsua
$ python run.py  mod_sipp.py scripts-sipp/uac-upd-sdp-decline.xml

### Log, call stack, etc

```shell
pjsua0: 10:25:39.921           pjsua_call.c  .....Call 0: received updated media offer
pjsua0: 10:25:39.921      inv0x7fe7a0003b68  .....SDP negotiation done: No suitable codec for remote offer (PJMEDIA_SDPNEG_NOANSCODEC)
pjsua0: 10:25:39.921           pjsua_call.c  ......SDP negotiation has failed: No suitable codec for remote offer (PJMEDIA_SDPNEG_NOANSCODEC) [status=220049]
pjsua0: 10:25:39.921           pjsua_core.c  .........TX 410 bytes Response msg 415/INVITE/cseq=1 (tdta0x7fe7a0023af8) to UDP 127.0.0.1:50070:
pjsua0: SIP/2.0 415 Unsupported Media Type
pjsua0: Via: SIP/2.0/UDP 127.0.0.1:50070;received=127.0.0.1;branch=z9hG4bK-1244-1-0
pjsua0: Call-ID: 1-1244@127.0.0.1
pjsua0: From: "sipp" <sip:sipp@127.0.0.1>;tag=1244SIPpTag091
pjsua0: To: "service" <sip:service@127.0.0.1>;tag=bda40eb6-b9d9-4ca2-b3ed-836201a5d063
pjsua0: CSeq: 1 INVITE
pjsua0: Allow: PRACK, INVITE, ACK, BYE, CANCEL, UPDATE, INFO, SUBSCRIBE, NOTIFY, REFER, MESSAGE, OPTIONS
pjsua0: Content-Length:  0
pjsua0:
pjsua0:
pjsua0: --end msg--
pjsua0: ================== send call answer 200 ================== [at t=000]
pjsua0: ================== expect state.*CONFIRMED ================== [at t=000]
pjsua0: 10:25:39.921          pjsua_media.c  ............Call 0: deinitializing media..
pjsua0: 10:25:39.921          pjsua_media.c  .............
pjsua0:   [DISCONNCTD] To: "sipp" <sip:sipp@127.0.0.1>;tag=1244SIPpTag091
pjsua0: Call time: 00h:00m:00s, 1st res in 35 ms, conn in 0ms
pjsua0: #0 audio deactivated
pjsua0: 10:25:39.921          pjsua_media.c  ..............Media stream call00:0 is destroyed
pjsua0: 10:25:39.921      udp0x7fe7a000dbf0  .............UDP media transport stopped
pjsua0: 10:25:39.921      udp0x7fe7a000dbf0  .............UDP media transport destroyed
pjsua0: 10:25:39.921            pjsua_app.c  ............Call 0 is DISCONNECTED [reason=415 (Unsupported Media Type)]
pjsua0: 10:25:39.921           pjsua_core.c  .......TX 309 bytes Response msg 488/UPDATE/cseq=3 (tdta0x7fe7a0020ab8) to UDP 127.0.0.1:50070:
pjsua0: SIP/2.0 488 Not Acceptable Here
pjsua0: Via: SIP/2.0/UDP 127.0.0.1:50070;received=127.0.0.1;branch=z9hG4bK-1244-1-5
pjsua0: Call-ID: 1-1244@127.0.0.1
pjsua0: From: "sipp" <sip:sipp@127.0.0.1>;tag=1244SIPpTag091
pjsua0: To: "service" <sip:service@127.0.0.1>;tag=bda40eb6-b9d9-4ca2-b3ed-836201a5d063
pjsua0: CSeq: 3 UPDATE
pjsua0: Content-Length:  0
pjsua0:
pjsua0:
pjsua0: --end msg--
```

### PR DESCRIPTION
**Pull request by vasilevalex**
Fixes #3135

### CODE REVIEW

**Review by sauwming — APPROVED** [review]

File: pjsip/src/pjsua-lib/pjsua_call.c [hunk 1]
```diff
@@ -5204,6 +5204,7 @@ static void pjsua_call_on_media_update(pjsip_inv_session *inv,
 	 * UAS dialog and if this is not a re-INVITE
 	 */
 	if (inv->state != PJSIP_INV_STATE_NULL &&
+	    inv->state != PJSIP_INV_STATE_EARLY &&
```
Comment (nanangizz) [inline pjsip/src/pjsua-lib/pjsua_call.c:5207]: This patch seems to cause a behavior change, i.e: if the SDP offer/answer nego from INVITE transaction (not UPDATE) fails, the call will be no longer disconnected, or even the call will never get disconnected on any SDP nego failure.

As the reported issue seems to be SDP nego failure of UPDATE while processing the initial INVITE, the fix should affect that specific scenario only. Unfortunately the callback does not provide `tsx` or `rdata` info, so we cannot check if it is SDP offer/answer from UPDATE, but perhaps we can use `call->med_cnt` info for checking whether there has been a successful SDP nego before (from INVITE+18x)?

Comment (vasilevalex) [reply pjsip/src/pjsua-lib/pjsua_call.c:5207]: Hi @nanangizz , this issue was found, trying to fix #2967, so yes it should affect not only UPDATE, but also PRACK SDP offer/answer negotiation.
I tried, but I really can't imagine the scenario, when the call in EARLY state must be disconnected. Can you please describe the scenario? Then I can prepare the sipp test, that is failing and fix it.

Comment (nanangizz) [reply pjsip/src/pjsua-lib/pjsua_call.c:5207]: AFAIK, the current behavior of PJSUA lib is as follow:

For UAC:
1. send INVITE with SDP offer
2. recv 183 with SDP answer
3. when UAC sees failure in SDP nego, it will disconnect call (by sending CANCEL)

For UAS:
1. receive INVITE with SDP offer
2. generate SDP answer (e.g: for 183 or 200 response)
3. the generated answer will be negotiated with the offer, if it fails, call will be disconnected

The proposed patch seems to change this behavior?

Comment (vasilevalex) [reply pjsip/src/pjsua-lib/pjsua_call.c:5207]: I prepared UAC and UAS tests with 3 different unacceptable SDP:
1) audio codec that is not supported by pjsua 
2) media type video, instead of audio
3) SDP version=1 (must be v=0)
Don't be confused by test names, they show the role of sipp (uac/uas)

First of all, I can confirm, that this patch changes behavior in one case (pjsua is UAC and receives 183 with SDP media type=video) uas-answer-183-wrong-media.xml
It can be fixed for example with this not too elegant code:
```
 if ((inv->state != PJSIP_INV_STATE_NULL &&
    inv->state != PJSIP_INV_STATE_EARLY &&
    inv->state != PJSIP_INV_STATE_CONFIRMED) ||
    (inv->state == PJSIP_INV_STATE_EARLY && call->med_cnt == 0))
```
Interesting case is number 3. Pjsua receives completely wrong SDP. It does not work correctly in both UAC/UAS scenarios even without any patches, but using current source code.
When pjsua is UAC (uas-answer-183-wrong-version.xml) it detects an error `Error parsing/validating SDP body: Invalid SDP version line`, but never disconnects the call.
When pjsua is UAS (uac-183-wrong-version.xml) it answers `400 Bad SDP`, receives ACK, but continues retransmitting "400 Bad SDP". Call is not disconnected too.
Function `inv_on_state_early` never checks return status of `inv_check_sdp_in_incoming_msg`.
Tests are attached.
[uas-answer-183-wrong-version.xml.txt](https://github.com/pjsip/pjproject/files/9828542/uas-answer-183-wrong-version.xml.txt)
[uas-answer-183-wrong-version.py.txt](https://github.com/pjsip/pjproject/files/9828543/uas-answer-183-wrong-version.py.txt)
[uas-answer-183-wrong-media.xml.txt](https://github.com/pjsip/pjproject/files/9828544/uas-answer-183-wrong-media.xml.txt)
[uas-answer-183-wrong-media.py.txt](https://github.com/pjsip/pjproject/files/9828545/uas-answer-183-wrong-media.py.txt)
[uas-answer-183-wrong-codec.xml.txt](https://github.com/pjsip/pjproject/files/9828546/uas-answer-183-wrong-codec.xml.txt)
[uas-answer-183-wrong-codec.py.txt](https://github.com/pjsip/pjproject/files/9828547/uas-answer-183-wrong-codec.py.txt)
[uac-183-wrong-version.xml.txt](https://github.com/pjsip/pjproject/files/9828548/uac-183-wrong-version.xml.txt)
[uac-183-wrong-version.py.txt](https://github.com/pjsip/pjproject/files/9828549/uac-183-wrong-version.py.txt)
[uac-183-wrong-media.xml.txt](https://github.com/pjsip/pjproject/files/9828550/uac-183-wrong-media.xml.txt)
[uac-183-wrong-media.py.txt](https://github.com/pjsip/pjproject/files/9828551/uac-183-wrong-media.py.txt)
[uac-183-wrong-codec.xml.txt](https://github.com/pjsip/pjproject/files/9828552/uac-183-wrong-codec.xml.txt)
[uac-183-wrong-codec.py.txt](https://github.com/pjsip/pjproject/files/9828553/uac-183-wrong-codec.py.txt)

Comment (nanangizz) [reply pjsip/src/pjsua-lib/pjsua_call.c:5207]: Thanks for the pjsua/sipp tests! So the behavior change is confirmed and we need to fix it. And regarding case no 3, perhaps we should create a separate issue/PR? Good catch btw.

Comment (sauwming) [reply pjsip/src/pjsua-lib/pjsua_call.c:5207]: > ```
>  if ((inv->state != PJSIP_INV_STATE_NULL &&
>     inv->state != PJSIP_INV_STATE_EARLY &&
>     inv->state != PJSIP_INV_STATE_CONFIRMED) ||
>     (inv->state == PJSIP_INV_STATE_EARLY && call->med_cnt == 0))
> ```

I'm wondering if checking `if (call->med_cnt == 0)` only actually is sufficient here? since we should only disconnect the call if there's no media, otherwise we should revert the previous media.

Comment (vasilevalex) [reply pjsip/src/pjsua-lib/pjsua_call.c:5207]: @sauwming I'm completely newbie in pjproject code, so I'm not 100% sure, that `(call->med_cnt == 0)` covers all the cases, when call should be disconnected in EARLY state. It's worth to make tests with incompatible SDP for late negotiation for example. But they should also have `call->med_cnt == 0`
According to RFC 6337 section 2.2 (https://datatracker.ietf.org/doc/html/rfc6337#section-2.2) only PRACK and UPDATE can send SDP offer in EARLY state, but `call->med_cnt == 1` in these cases.
Actually, all these tests with wrong SDP in 183 are emulating evil UAS, because normal response must be 488 or something similar. There can be other unpredictable cases, which break RFCs.
@nanangizz I'll create one more issue for 183 reply with broken SDP (e.g. v=1)

Comment (nanangizz) [reply pjsip/src/pjsua-lib/pjsua_call.c:5207]: Also, adding some comments (and/or add link to this PR) about the new added checks is usually useful for future ref.

**Review by nanangizz — APPROVED** [review]

**Review by sauwming — APPROVED** [review]
