### PR TITLE
[Fix #3385 Assertion error] return status for proper status checking afterwards

### LINKED ISSUE #3385: Assertion `snd_port && port' failed caused by stale status check in simpleua.c
### Describe the bug

This assertion occurs in `simpleua.c:call_on_media_update()`. Simpleua is trying to connect the sound port when sound port is not created properly. Although checks exist in port creation functions, simpleua did not update the `status` variable, causing it to hit this unexpected assertion error. 

### Steps to reproduce

* Launch SIP Simple UA service: `./pjproject/pjsip-apps/bin/samples/x86_64-unknown-linux-gnu/simpleua sip:user@127.0.0.1:5061`
* Launch Baresip client: `./baresip -f docs/examples -n 127.0.0.1 -e \"/accept\"
`

### PJSIP version

2.13-dev, 2.13, 2.8

### Context

The root cause is straightforward and I have not spotted other issues in pjsip library other than it affecting the simpleua sample application itself. I verified that the assertion error was triggered due to `g_snd_port` variable remaining NULL after `pjmedia_snd_port_create()`. Although in `sound_port.c`, status is properly set when the sound port fails to be updated, the problem is that the status check on line 920 in `simpleua.c` is on a stale `status` value since this variable was not set upon returns of function `pjmedia_transport_media_start()`, `pjmedia_stream_get_port()` and `pjmedia_snd_port_create()`. 

I came up with a patch [0001-return-status-for-proper-status-checking-afterwards.patch](https://github.com/pjsip/pjproject/files/10735023/0001-return-status-for-proper-status-checking-afterwards.patch). I verified that it works. Please help me double check if the fix makes sense. Much appreciated!

### Log, call stack, etc

```shell
=======================Assertion=======================
simpleua: ../src/pjmedia/sound_port.c:753: pj_status_t pjmedia_snd_port_connect(pjmedia_snd_port *, pjmedia_port *): Assertion `snd_port && port' failed.

=======================Log=======================
20:42:55.952         os_core_unix.c !pjlib 2.13 for POSIX initialized
20:42:55.952         sip_endpoint.c  Creating endpoint instance...
20:42:55.952                  pjlib  select() I/O Queue created (0x6280000031c0)
20:42:55.952         sip_endpoint.c  Module "mod-msg-print" registered
20:42:55.952        sip_transport.c  Transport manager created.
20:42:55.953      udp0x615000000080  SIP UDP transport started, published address is 172.17.0.2:5060
20:42:55.953         sip_endpoint.c  Module "mod-tsx-layer" registered
20:42:55.953         sip_endpoint.c  Module "mod-stateful-util" registered
20:42:55.953         sip_endpoint.c  Module "mod-ua" registered
20:42:55.953         sip_endpoint.c  Module "mod-invite" registered
20:42:55.953         sip_endpoint.c  Module "mod-100rel" registered
20:42:55.953         sip_endpoint.c  Module "mod-simpleua" registered
20:42:55.953         sip_endpoint.c  Module "mod-msg-log" registered
20:42:55.954                  pjlib  select() I/O Queue created (0x61f0000000a8)
20:42:55.954      dlg0x61d000000b28  UAC dialog created
20:42:55.955      dlg0x61d000000b28  Module mod-invite added as dialog usage, data=0x6190000019a8
20:42:55.955      dlg0x61d000000b28  .Session count inc to 2 by mod-invite
20:42:55.955      dlg0x61d000000b28  Module mod-100rel added as dialog usage, data=0x619000001cd8
20:42:55.955      dlg0x61d000000b28  100rel module attached
20:42:55.955      inv0x61d000000b28  UAC invite session created for dialog dlg0x61d000000b28
20:42:55.955               endpoint  Request msg INVITE/cseq=124 (tdta0x62100001a5a8) created.
20:42:55.955      inv0x61d000000b28  .Sending Request msg INVITE/cseq=124 (tdta0x62100001a5a8)
20:42:55.955      dlg0x61d000000b28  ..Sending Request msg INVITE/cseq=124 (tdta0x62100001a5a8)
20:42:55.955      tsx0x61d000001528  ...Transaction created for Request msg INVITE/cseq=124 (tdta0x62100001a5a8)
20:42:55.955      tsx0x61d000001528  ..Sending Request msg INVITE/cseq=124 (tdta0x62100001a5a8) in state Null
20:42:55.955          sip_resolve.c  ...Target '127.0.0.1:5061' type=Unspecified resolved to '127.0.0.1:5061' type=UDP (UDP transport)
20:42:55.955             simpleua.c  ...TX 727 bytes Request msg INVITE/cseq=124 (tdta0x62100001a5a8) to UDP 127.0.0.1:5061:
INVITE sip:user@127.0.0.1:5061 SIP/2.0

Via: SIP/2.0/UDP 172.17.0.2:5060;rport;branch=z9hG4bKPjiNeUsXjdMuRBU2j.KGSI94O1i7pQoYqc

Max-Forwards: 70

From: <sip:simpleuac@172.17.0.2>;tag=PKcMBzp6yhIZQG-du1TsYkW1MPmX6L5V

To: sip:user@127.0.0.1

Contact: <sip:simpleuac@172.17.0.2:5060>

Call-ID: 2mdIf8lexOTBIMg2pPgKOBdDB3SowCcf

CSeq: 124 INVITE

Allow: INVITE, ACK, BYE, CANCEL, UPDATE

Supported: 

Content-Type: application/sdp

Content-Length:   272



v=0

o=- 3884359375 3884359375 IN IP4 172.17.0.2

s=pjmedia

t=0 0

m=audio 4000 RTP/AVP 0 8 120

c=IN IP4 172.17.0.2

b=TIAS:64000

a=rtcp:4001 IN IP4 172.17.0.2

a=sendrecv

a=rtpmap:0 PCMU/8000

a=rtpmap:8 PCMA/8000

a=rtpmap:120 telephone-event/8000

a=fmtp:120 0-16


--end msg--
20:42:55.955      tsx0x61d000001528  ...State changed from Null to Calling, event=TX_MSG
20:42:55.955      dlg0x61d000000b28  ....Transaction tsx0x61d000001528 state changed to Calling
20:42:55.955             simpleua.c  .....Call state changed to CALLING
20:42:56.455      tsx0x61d000001528  Retransmit timer event
20:42:56.455      tsx0x61d000001528  .Retransmiting Request msg INVITE/cseq=124 (tdta0x62100001a5a8), count=0, restart?=1
20:42:56.455             simpleua.c  .TX 727 bytes Request msg INVITE/cseq=124 (tdta0x62100001a5a8) to UDP 127.0.0.1:5061:
INVITE sip:user@127.0.0.1:5061 SIP/2.0

Via: SIP/2.0/UDP 172.17.0.2:5060;rport;branch=z9hG4bKPjiNeUsXjdMuRBU2j.KGSI94O1i7pQoYqc

Max-Forwards: 70

From: <sip:simpleuac@172.17.0.2>;tag=PKcMBzp6yhIZQG-du1TsYkW1MPmX6L5V

To: sip:user@127.0.0.1

Contact: <sip:simpleuac@172.17.0.2:5060>

Call-ID: 2mdIf8lexOTBIMg2pPgKOBdDB3SowCcf

CSeq: 124 INVITE

Allow: INVITE, ACK, BYE, CANCEL, UPDATE

Supported: 

Content-Type: application/sdp

Content-Length:   272



v=0

o=- 3884359375 3884359375 IN IP4 172.17.0.2

s=pjmedia

t=0 0

m=audio 4000 RTP/AVP 0 8 120

c=IN IP4 172.17.0.2

b=TIAS:64000

a=rtcp:4001 IN IP4 172.17.0.2

a=sendrecv

a=rtpmap:0 PCMU/8000

a=rtpmap:8 PCMA/8000

a=rtpmap:120 telephone-event/8000

a=fmtp:120 0-16


--end msg--
20:42:56.457         sip_endpoint.c  Processing incoming message: Response msg 180/INVITE/cseq=124 (rdata0x625000000128)
20:42:56.457             simpleua.c  .RX 491 bytes Response msg 180/INVITE/cseq=124 (rdata0x625000000128) from UDP 127.0.0.1:5061:
SIP/2.0 180 Ringing

Via: SIP/2.0/UDP 172.17.0.2:5060;branch=z9hG4bKPjiNeUsXjdMuRBU2j.KGSI94O1i7pQoYqc;rport=5060;received=127.0.0.1

From: <sip:simpleuac@172.17.0.2>;tag=PKcMBzp6yhIZQG-du1TsYkW1MPmX6L5V

To: sip:user@127.0.0.1;tag=9800a88ace9f4c6d

Call-ID: 2mdIf8lexOTBIMg2pPgKOBdDB3SowCcf

CSeq: 124 INVITE

Server: baresip v0.6.2 (x86_64/linux)

Contact: <sip:user-0x2571180@127.0.0.1:5061>

Allow: INVITE,ACK,BYE,CANCEL,OPTIONS,NOTIFY,SUBSCRIBE,INFO,MESSAGE,REFER

Content-Length: 0




--end msg--
20:42:56.457      tsx0x61d000001528  .Incoming Response msg 180/INVITE/cseq=124 (rdata0x625000000128) in state Calling
20:42:56.457      tsx0x61d000001528  ..State changed from Calling to Proceeding, event=RX_MSG
20:42:56.457      dlg0x61d000000b28  ...Received Response msg 180/INVITE/cseq=124 (rdata0x625000000128)
20:42:56.457      dlg0x61d000000b28  ....Route-set updated
20:42:56.457      dlg0x61d000000b28  ...Transaction tsx0x61d000001528 state changed to Proceeding
20:42:56.457             simpleua.c  ....Call state changed to EARLY
20:42:56.458         sip_endpoint.c  Processing incoming message: Response msg 200/INVITE/cseq=124 (rdata0x625000007928)
20:42:56.458             simpleua.c  .RX 847 bytes Response msg 200/INVITE/cseq=124 (rdata0x625000007928) from UDP 127.0.0.1:5061:
SIP/2.0 200 Answering

Via: SIP/2.0/UDP 172.17.0.2:5060;branch=z9hG4bKPjiNeUsXjdMuRBU2j.KGSI94O1i7pQoYqc;rport=5060;2eceived=127.0.0.1

From: <sip:simpleuac@172.17.0.2>;tag=PKcMBzp6yhIZQG-du1TsYkW1MPmX6L5V

To: sip:user@127.0.0.1;tag=0208f9b55a9338db

Call-ID: 2mdIf8lexOTBIMg2pPgKOBdDB3SowCcf

CSeq: 124 INVITE

Server: baresip v0.6.2 (x86_64/linux)

Contact: <sip:user-0xbd6010@127.0.0.1:5061>

Allow: INVITE,ACK,BYE,CANCEL,OPTIONS,NOTIFY,SUBSCRIBE,INFO,MESSAGE,REFER

Content-Type: application/sdp

Content-Length: 322



v=0

o=- 2326633173 457886378 IN IP4 127.0.0.1

s=-

c=IN IP4 127.0.0.1

t=0 0

a=tool:baresip 0.6.2

m=audio 48860 RTP/AVP 0 8 120

a=rtpmap:0 PCMU/8000

a=rtpmap:8 PCMA/8000

a=rtpmap:120 telephone-event/8000

a=fmtp:120 0-15

a=sendrecv

a=label:1

a=rtcp-rsize

a=ssrc:2468915352 cname:sip:user@127.0.0.1

a=ptime:20


--end msg--
20:42:56.458      tsx0x61d000001528  .Incoming Response msg 200/INVITE/cseq=124 (rdata0x625000007928) in state Proceeding
20:42:56.458      tsx0x61d000001528  ..State changed from Proceeding to Terminated, event=RX_MSG
20:42:56.458         sip_ua_layer.c  ...Received forked Response msg 200/INVITE/cseq=124 (rdata0x625000007928) for existing dialog dlg0x61d000000b28
20:42:56.458         sip_ua_layer.c  ...Unhandled forked Response msg 200/INVITE/cseq=124 (rdata0x625000007928) from 127.0.0.1:5061, response will be handed over to the first dialog
20:42:56.458      dlg0x61d000000b28  ...Received Response msg 200/INVITE/cseq=124 (rdata0x625000007928)
20:42:56.458      dlg0x61d000000b28  ....Route-set updated
20:42:56.458      dlg0x61d000000b28  ....Route-set frozen
20:42:56.458      dlg0x61d000000b28  ...Transaction tsx0x61d000001528 state changed to Terminated
20:42:56.458             simpleua.c  ....Call state changed to CONNECTING
20:42:56.458      inv0x61d000000b28  ....Got SDP answer in Response msg 200/INVITE/cseq=124 (rdata0x625000007928)
20:42:56.458      inv0x61d000000b28  ....SDP negotiation done: Success
20:42:56.458     strm0x622000000128  ....VAD temporarily disabled
20:42:56.458     strm0x622000000128  ....Jitter buffer reset
20:42:56.458                  rtp.c  ....pjmedia_rtp_session_init: ses=0x61500000e318, default_pt=0, ssrc=0x25e45d32
20:42:56.458                  rtp.c  ....pjmedia_rtp_session_init2: ses=0x61500000e318, seq=1118, ts=0, peer_ssrc=-1826051944
20:42:56.458                  rtp.c  ....pjmedia_rtp_session_init: ses=0x619000002c30, default_pt=0, ssrc=0x25e45d32
20:42:56.458                  rtp.c  ....pjmedia_rtp_session_init2: ses=0x619000002c30, seq=10452, ts=0, peer_ssrc=-1826051944
20:42:56.458      udp0x61500000c880  ....UDP media transport attached
20:42:56.458               stream.c  ....Stream strm0x622000000128 created
20:42:56.458     strm0x622000000128  ....Encoder stream started
20:42:56.458     strm0x622000000128  ....Decoder stream started
20:42:56.458      udp0x61500000c880  ....UDP media transport started

simpleua: ../src/pjmedia/sound_port.c:753: pj_status_t pjmedia_snd_port_connect(pjmedia_snd_port *, pjmedia_port *): Assertion `snd_port && port' failed.

=======================Stack=======================
    #1 0x5dd8ff in pjmedia_snd_port_connect /root/server-afl/programs/sip/pjproject/pjmedia/build/../src/pjmedia/sound_port.c:753:5
    #2 0x4f1966 in call_on_media_update /root/server-afl/programs/sip/pjproject/pjsip-apps/build/../src/samples/simpleua.c:931:14
    #3 0x50539e in inv_negotiate_sdp /root/server-afl/programs/sip/pjproject/pjsip/build/../src/pjsip-ua/sip_inv.c:2153:9
    #4 0x504c67 in inv_check_sdp_in_incoming_msg /root/server-afl/programs/sip/pjproject/pjsip/build/../src/pjsip-ua/sip_inv.c:2391:9
    #5 0x50a3e1 in inv_on_state_early /root/server-afl/programs/sip/pjproject/pjsip/build/../src/pjsip-ua/sip_inv.c:4759:21
    #6 0x503333 in mod_inv_on_tsx_state /root/server-afl/programs/sip/pjproject/pjsip/build/../src/pjsip-ua/sip_inv.c:744:5
    #7 0x5ad6e7 in pjsip_dlg_on_tsx_state /root/server-afl/programs/sip/pjproject/pjsip/build/../src/pjsip/sip_dialog.c:2143:9
    #8 0x5b2388 in mod_ua_on_tsx_state /root/server-afl/programs/sip/pjproject/pjsip/build/../src/pjsip/sip_ua_layer.c:186:5
    #9 0x592bda in tsx_set_state /root/server-afl/programs/sip/pjproject/pjsip/build/../src/pjsip/sip_transaction.c
    #10 0x597f7a in tsx_on_state_proceeding_uac /root/server-afl/programs/sip/pjproject/pjsip/build/../src/pjsip/sip_transaction.c:3100:13
    #11 0x59410e in pjsip_tsx_recv_msg /root/server-afl/programs/sip/pjproject/pjsip/build/../src/pjsip/sip_transaction.c:1902:5
    #12 0x595d85 in mod_tsx_layer_on_rx_response /root/server-afl/programs/sip/pjproject/pjsip/build/../src/pjsip/sip_transaction.c:932:5
    #13 0x556822 in pjsip_endpt_process_rx_data /root/server-afl/programs/sip/pjproject/pjsip/build/../src/pjsip/sip_endpoint.c:937:27
    #14 0x554b5a in endpt_on_rx_msg /root/server-afl/programs/sip/pjproject/pjsip/build/../src/pjsip/sip_endpoint.c:1079:5
    #15 0x572dc7 in pjsip_tpmgr_receive_packet /root/server-afl/programs/sip/pjproject/pjsip/build/../src/pjsip/sip_transport.c:2199:9
    #16 0x57b307 in udp_on_read_complete /root/server-afl/programs/sip/pjproject/pjsip/build/../src/pjsip/sip_transport_udp.c:193:17
    #17 0x759bf4 in ioqueue_dispatch_read_event /root/server-afl/programs/sip/pjproject/pjlib/build/../src/pj/ioqueue_common_abs.c:609:13
    #18 0x761fb0 in pj_ioqueue_poll /root/server-afl/programs/sip/pjproject/pjlib/build/../src/pj/ioqueue_select.c:1109:21
    #19 0x555cdc in pjsip_endpt_handle_events2 /root/server-afl/programs/sip/pjproject/pjsip/build/../src/pjsip/sip_endpoint.c:744:13
    #20 0x4f08ee in main /root/server-afl/programs/sip/pjproject/pjsip-apps/build/../src/samples/simpleua.c:568:9
    #21 0x7f76fdbf883f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2083f)
    #22 0x41b2b8 in _start (/root/server-afl/programs/sip/pjproject/pjsip-apps/bin/samples/x86_64-unknown-linux-gnu/simpleua+0x41b2b8)
```

### PR DESCRIPTION
**Pull request by Kexin6**
This is my proposed fix for #3385 `Assertion 'snd_port && port' failed`. Since it is a straightforward change in `simpleua.c`, I am creating a PR directly. Please review my PR if you have time. Thanks!

### CODE REVIEW

File: pjsip-apps/src/samples/simpleua.c [hunk 1]
```diff
@@ -896,18 +896,18 @@ static void call_on_media_update( pjsip_inv_session *inv,
     }
 
     /* Start the UDP media transport */
-    pjmedia_transport_media_start(g_med_transport[0], 0, 0, 0, 0);
+    status = pjmedia_transport_media_start(g_med_transport[0], 0, 0, 0, 0);
```
Comment (sauwming) [inline pjsip-apps/src/samples/simpleua.c:899]: add `pj_assert(status == PJ_SUCCESS)` here, or `if (status != PJ_SUCCESS) {print_some_log; return;}`

Otherwise the returned status will be useless. May as well remove it (back to the original version), which is actually okay since as mentioned previously, these sample apps are not meant to have the most comprehensive error checking.

Comment (Kexin6) [reply pjsip-apps/src/samples/simpleua.c:899]: Hi @sauwming, thanks for pointing out. Please see my updated commit.

**Review by sauwming — APPROVED** [review]
