### PR TITLE
Fixed buffer overflow in Android video codec

### LINKED ISSUE #4404: Android - Fatal signal 11 (SIGSEGV) on attended transfer of video call
### Describe the bug

When attended video call transfer is performed, and one of devices has higher video resolution, the transfer targeting device crashes.

### Steps to reproduce

1. Configure three devices with extensions 6003, 6004, 6005.
2. 6003 and 6005 are PJSUA2 Android devices with video resolution 288x352 and codec H.264.
3. 6004 is Windows Linphone device with video resolution 1280x720 and codec H.264.
4. Start a video call from 6003 to 6004, answer it.
5. On 6003 put the call on hold.
6. On 6003 start a video call to 6005, answer it.
7. On 6004 make an attended transfer, replacing itself with 6004.
8. When the video call is established between 6004 and 6005, the 6005 device crashes with SIGSEGV 11.

### PJSIP version

2.15

### Context

Seems like from the 6005 point of view, it has the same SIP call, initially with 6003 and then with 6004.
At the beginning the call between 6003 and 6005 is negotiated to the 288x352 video resolution.
After the attended transfer 6004 transmits the video stream with it's configured resolution 1280x720.
But 6005 already has a negotiated video stream 288x352, so it crashes somewhere at pj_memcpy().

### Log, call stack, etc

```shell
2025-04-18 15:50:06.687 pjsua2           com.example       D            pjsua_core.c !.RX 1045 bytes Request msg INVITE/cseq=104 (rdata0x7009f8c75d98) from UDP 192.168.0.100:5060:
INVITE sip:6005@192.168.0.130:55317;ob SIP/2.0
Via: SIP/2.0/UDP 192.168.0.100:5060;branch=z9hG4bK51dbfa29;rport
Max-Forwards: 70
From: "vlad1" <sip:6004@192.168.0.100>;tag=as36940ff6
To: <sip:6005@192.168.0.130:55317;ob>;tag=de2f4d14-bcad-4ca0-910d-44cc30cb7cc1
Contact: <sip:6004@192.168.0.100:5060>
Call-ID: 4c83b9d83edd75602228f31533bbf725@192.168.0.100:5060
CSeq: 104 INVITE
User-Agent: Asterisk PBX certified-18.9-cert13
Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, SUBSCRIBE, NOTIFY, INFO, PUBLISH, MESSAGE
Supported: replaces, timer
P-Asserted-Identity: "vlad" <sip:6003@192.168.0.100>
Content-Type: application/sdp
Content-Length: 382

v=0
o=root 713425523 713425524 IN IP4 192.168.0.100
s=Asterisk PBX certified-18.9-cert13
c=IN IP4 192.168.0.100
b=CT:384
t=0 0
m=audio 12310 RTP/AVP 0 101
a=rtpmap:0 PCMU/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-16
a=maxptime:150
a=sendrecv
m=video 14272 RTP/AVP 99
a=rtpmap:99 H264/90000
a=fmtp:99 packetization-mode=1;profile-level-id=42E01F
a=sendrecv

--end msg--
2025-04-18 15:50:06.688 pjsua2           com.example  D            pjsua_call.c  .....Call 0: received updated media offer
2025-04-18 15:50:06.688 pjsua2           com.example  D           pjsua_media.c  ......Call 0: re-initializing media..
2025-04-18 15:50:06.688 pjsua2           com.example  D           pjsua_media.c  .......Media index 0 selected for audio call 0
2025-04-18 15:50:06.689 pjsua2           com.example  D       inv0x7009c8c60308  .....SDP negotiation done: Success
2025-04-18 15:50:06.689 pjsua2           com.example  D           pjsua_media.c  ......Call 0: updating media..
2025-04-18 15:50:06.690 pjsua2           com.example  D           pjsua_media.c  .......Call 0: stream #0 (audio) unchanged.
2025-04-18 15:50:06.690 pjsua2           com.example  D           pjsua_media.c  .......Audio updated, stream #0: PCMU (sendrecv)
2025-04-18 15:50:06.691 pjsua2           com.example  D           pjsua_media.c  .......Call 0: stream #1 (video) unchanged.
2025-04-18 15:50:06.692 pjsua2           com.example  D           pjsua_media.c  .......Video updated, stream #1: H264 (sendrecv)
2025-04-18 15:50:06.692 SipFeature       com.example  D  MediaState: call #0, idx:0, type:audio, status:active, dir:enc/dec
2025-04-18 15:50:06.693 SipFeature       com.example  D  MediaState: call #0, idx:1, type:video, status:active, dir:enc/dec
2025-04-18 15:50:06.693 pjsua2           com.example  D             pjsua_aud.c !Conf connect: 0 --> 1
2025-04-18 15:50:06.694 pjsua2           com.example  D            conference.c !..Connect ports 0->1 queued
2025-04-18 15:50:06.696 pjsua2           com.example  D            pjsua_core.c !........TX 1140 bytes Response msg 200/INVITE/cseq=104 (tdta0x7009c8df8c78) to UDP 192.168.0.100:5060:
SIP/2.0 200 OK
Via: SIP/2.0/UDP 192.168.0.100:5060;rport=5060;received=192.168.0.100;branch=z9hG4bK51dbfa29
Call-ID: 4c83b9d83edd75602228f31533bbf725@192.168.0.100:5060
From: "vlad1" <sip:6004@192.168.0.100>;tag=as36940ff6
To: <sip:6005@192.168.0.130;ob>;tag=de2f4d14-bcad-4ca0-910d-44cc30cb7cc1
CSeq: 104 INVITE
Contact: <sip:6005@192.168.0.130:55317;ob>
Allow: PRACK, INVITE, ACK, BYE, CANCEL, UPDATE, INFO, SUBSCRIBE, NOTIFY, REFER, MESSAGE, OPTIONS
Supported: replaces, 100rel, timer, siprec, norefersub, trickle-ice
Content-Type: application/sdp
Content-Length:   554

v=0
o=- 3953969391 3953969392 IN IP4 10.0.2.16
s=pjmedia
b=AS:352
t=0 0
a=X-nat:0
m=audio 4000 RTP/AVP 0 101
c=IN IP4 10.0.2.16
b=TIAS:64000
a=rtcp:4001 IN IP4 10.0.2.16
a=sendrecv
a=rtpmap:0 PCMU/8000
a=ssrc:1188117598 cname:5c45e91157985721
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-16
m=video 4002 RTP/AVP 99
c=IN IP4 10.0.2.16
b=TIAS:256000
a=rtcp:4003 IN IP4 10.0.2.16
a=sendrecv
a=rtpmap:99 H264/90000
a=fmtp:99 profile-level-id=42e01f; packetization-mode=1
a=ssrc:231418129 cname:5c45e91157985721
a=rtcp-fb:* nack pli

--end msg--
2025-04-18 15:50:06.696 pjsua2           com.example       D             pjsua_aud.c  Conf connect: 1 --> 0
2025-04-18 15:50:06.696 pjsua2           com.example       D            conference.c  ..Connect ports 1->0 queued
2025-04-18 15:50:06.700 pjsua2           com.example       D            pjsua_core.c !.RX 450 bytes Request msg ACK/cseq=104 (rdata0x7009f8c75d98) from UDP 192.168.0.100:5060:
ACK sip:6005@192.168.0.130:55317;ob SIP/2.0
Via: SIP/2.0/UDP 192.168.0.100:5060;branch=z9hG4bK5890ca8c;rport
Max-Forwards: 70
From: "vlad1" <sip:6004@192.168.0.100>;tag=as36940ff6
To: <sip:6005@192.168.0.130:55317;ob>;tag=de2f4d14-bcad-4ca0-910d-44cc30cb7cc1
Contact: <sip:6004@192.168.0.100:5060>
Call-ID: 4c83b9d83edd75602228f31533bbf725@192.168.0.100:5060
CSeq: 104 ACK
User-Agent: Asterisk PBX certified-18.9-cert13
Content-Length: 0


--end msg--
2025-04-18 15:50:06.710 pjsua2           com.example       D            conference.c !.Ports connection 0->1 already exists
2025-04-18 15:50:06.711 pjsua2           com.example       D            conference.c  .Ports connection 1->0 already exists
2025-04-18 15:50:06.718 pjsua2           com.example       D      strm0x7009f8c64d18 !Jitter buffer reset
2025-04-18 15:50:06.782 pjsua2           com.example       D  and_vid_mediacodec.cpp  Decoder failed to get output Buffer[0]
2025-04-18 15:50:06.782 pjsua2           com.example       D  and_vid_mediacodec.cpp  Decoder couldn't produce output frame
2025-04-18 15:50:06.883 pjsua2           com.example       D           pjsua_media.c !Sending video keyframe request via SIP INFO
2025-04-18 15:50:06.883 pjsua2           com.example       D            pjsua_call.c  Call 0 sending INFO request..
2025-04-18 15:50:06.883 pjsua2           com.example       D            pjsua_core.c  ...TX 611 bytes Request msg INFO/cseq=13275 (tdta0x7009c8dfbca8) to UDP 192.168.0.100:5060:
INFO sip:6004@192.168.0.100:5060 SIP/2.0
Via: SIP/2.0/UDP 192.168.0.130:55317;rport;branch=z9hG4bKPjfb044350-987d-462c-a2e7-4df7203d3154
Max-Forwards: 70
From: <sip:6005@192.168.0.130;ob>;tag=de2f4d14-bcad-4ca0-910d-44cc30cb7cc1
To: "vlad1" <sip:6004@192.168.0.100>;tag=as36940ff6
Call-ID: 4c83b9d83edd75602228f31533bbf725@192.168.0.100:5060
CSeq: 13275 INFO
User-Agent: PJSUA2 2.15-dev
Content-Type: application/media_control+xml
Content-Length:   146

<?xml version="1.0" encoding="utf-8" ?><media_control><vc_primitive><to_encoder><picture_fast_update/></to_encoder></vc_primitive></media_control>
--end msg--
2025-04-18 15:50:06.886 pjsua2           com.example       D            pjsua_core.c !.RX 536 bytes Response msg 200/INFO/cseq=13275 (rdata0x7009f8c75d98) from UDP 192.168.0.100:5060:
SIP/2.0 200 OK
Via: SIP/2.0/UDP 192.168.0.130:55317;branch=z9hG4bKPjfb044350-987d-462c-a2e7-4df7203d3154;received=192.168.0.130;rport=55317
From: <sip:6005@192.168.0.130;ob>;tag=de2f4d14-bcad-4ca0-910d-44cc30cb7cc1
To: "vlad1" <sip:6004@192.168.0.100>;tag=as36940ff6
Call-ID: 4c83b9d83edd75602228f31533bbf725@192.168.0.100:5060
CSeq: 13275 INFO
Server: Asterisk PBX certified-18.9-cert13
Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, SUBSCRIBE, NOTIFY, INFO, PUBLISH, MESSAGE
Supported: replaces, timer
Content-Length: 0


--end msg--
--------- beginning of crash
2025-04-18 15:50:07.584 pjsua2           com.example       D  and_vid_mediacodec.cpp !Frame size changed to 1280x720
2025-04-18 15:50:07.586 libc             com.example       A  Fatal signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0x70080c292000 in tid 8157 (Thread-182), pid 8025 (com.example)
2025-04-18 15:50:07.600 pjsua2           com.example       D    vstdec0x700a28c8b1c8 ! Decoding format changed: 1280x720 I420<- 15/1(~15)fps
2025-04-18 15:50:07.602 pjsua2           com.example       D              vid_conf.c !.Update video port 1 queued
2025-04-18 15:50:07.602 pjsua2           com.example       D              vid_conf.c  .Update video port 0 queued
2025-04-18 15:50:07.611 SipFeature       com.example       D  MediaEvent: call #0, idx 1, FMT_CHANGED
2025-04-18 15:50:07.612 SipFeature       com.example       D  Update remote video size: 1280x720
2025-04-18 15:50:07.612 SipFeature       com.example       D  MediaEvent: call #0, idx 1, FMT_CHANGED
2025-04-18 15:50:07.656 SipFeature       com.example       I  Call #0 "vlad1" <sip:6004@192.168.0.100> state:CONFIRMED VIDEO
2025-04-18 15:50:07.683 SipCallFragment  com.example       D  Set camera surface: stream 288x352, size 448x547
2025-04-18 15:50:07.684 SipCallFragment  com.example       D  Set remote surface: stream 1280x720, size 1440x810
2025-04-18 15:50:07.932 DEBUG            pid-9220          A  Cmdline: com.example
2025-04-18 15:50:07.932 DEBUG            pid-9220          A  pid: 8025, tid: 8157, name: Thread-182  >>> com.com.example <<<
2025-04-18 15:50:07.934 DEBUG            pid-9220          A        #02 pc 0000000000418578  /data/app/~~JvgCV0-DB5RQK8W6lSPdPw==/com.example-UV3hsa0g-763pMxGoZMWVw==/lib/x86_64/libpjsua2.so (pj_memcpy(void*, void const*, unsigned long)+72) (BuildId: 0c29c5e7a865a47118ceccf14ff44d5a82e109ed)
2025-04-18 15:50:07.934 DEBUG            pid-9220          A        #03 pc 0000000000418cb5  /data/app/~~JvgCV0-DB5RQK8W6lSPdPw==/com.example-UV3hsa0g-763pMxGoZMWVw==/lib/x86_64/libpjsua2.so (write_yuv(unsigned char*, unsigned int, unsigned char*, int, int, int)+245) (BuildId: 0c29c5e7a865a47118ceccf14ff44d5a82e109ed)
2025-04-18 15:50:07.934 DEBUG            pid-9220          A        #04 pc 0000000000418a57  /data/app/~~JvgCV0-DB5RQK8W6lSPdPw==/com.example-UV3hsa0g-763pMxGoZMWVw==/lib/x86_64/libpjsua2.so (and_media_decode(pjmedia_vid_codec*, and_media_codec_data*, unsigned char*, unsigned int, int, pj_timestamp*, int, pjmedia_frame*)+1239) (BuildId: 0c29c5e7a865a47118ceccf14ff44d5a82e109ed)
2025-04-18 15:50:07.935 DEBUG            pid-9220          A        #05 pc 0000000000417ccd  /data/app/~~JvgCV0-DB5RQK8W6lSPdPw==/com.example-UV3hsa0g-763pMxGoZMWVw==/lib/x86_64/libpjsua2.so (decode_h264(pjmedia_vid_codec*, unsigned long, pjmedia_frame*, unsigned int, pjmedia_frame*)+1261) (BuildId: 0c29c5e7a865a47118ceccf14ff44d5a82e109ed)
2025-04-18 15:50:07.935 DEBUG            pid-9220          A        #06 pc 000000000041a33b  /data/app/~~JvgCV0-DB5RQK8W6lSPdPw==/com.example-UV3hsa0g-763pMxGoZMWVw==/lib/x86_64/libpjsua2.so (and_media_codec_decode(pjmedia_vid_codec*, unsigned long, pjmedia_frame*, unsigned int, pjmedia_frame*)+427) (BuildId: 0c29c5e7a865a47118ceccf14ff44d5a82e109ed)
2025-04-18 15:50:07.935 DEBUG            pid-9220          A        #07 pc 000000000048383b  /data/app/~~JvgCV0-DB5RQK8W6lSPdPw==/com.example-UV3hsa0g-763pMxGoZMWVw==/lib/x86_64/libpjsua2.so (pjmedia_vid_codec_decode+59) (BuildId: 0c29c5e7a865a47118ceccf14ff44d5a82e109ed)
2025-04-18 15:50:07.935 DEBUG            pid-9220          A        #08 pc 00000000004834b4  /data/app/~~JvgCV0-DB5RQK8W6lSPdPw==/com.example-UV3hsa0g-763pMxGoZMWVw==/lib/x86_64/libpjsua2.so (decode_frame+964) (BuildId: 0c29c5e7a865a47118ceccf14ff44d5a82e109ed)
2025-04-18 15:50:07.936 DEBUG            pid-9220          A        #09 pc 0000000000480c24  /data/app/~~JvgCV0-DB5RQK8W6lSPdPw==/com.example-UV3hsa0g-763pMxGoZMWVw==/lib/x86_64/libpjsua2.so (on_rx_rtp+1588) (BuildId: 0c29c5e7a865a47118ceccf14ff44d5a82e109ed)
2025-04-18 15:50:07.937 DEBUG            pid-9220          A        #10 pc 00000000004721d2  /data/app/~~JvgCV0-DB5RQK8W6lSPdPw==/com.example-UV3hsa0g-763pMxGoZMWVw==/lib/x86_64/libpjsua2.so (srtp_rtp_cb+162) (BuildId: 0c29c5e7a865a47118ceccf14ff44d5a82e109ed)
2025-04-18 15:50:07.937 DEBUG            pid-9220          A        #11 pc 00000000004770e2  /data/app/~~JvgCV0-DB5RQK8W6lSPdPw==/com.example-UV3hsa0g-763pMxGoZMWVw==/lib/x86_64/libpjsua2.so (call_rtp_cb+130) (BuildId: 0c29c5e7a865a47118ceccf14ff44d5a82e109ed)
2025-04-18 15:50:07.938 DEBUG            pid-9220          A        #12 pc 00000000004751a4  /data/app/~~JvgCV0-DB5RQK8W6lSPdPw==/com.example-UV3hsa0g-763pMxGoZMWVw==/lib/x86_64/libpjsua2.so (on_rx_rtp+324) (BuildId: 0c29c5e7a865a47118ceccf14ff44d5a82e109ed)
2025-04-18 15:50:07.939 DEBUG            pid-9220          A        #13 pc 000000000058c472  /data/app/~~JvgCV0-DB5RQK8W6lSPdPw==/com.example-UV3hsa0g-763pMxGoZMWVw==/lib/x86_64/libpjsua2.so (ioqueue_dispatch_read_event+978) (BuildId: 0c29c5e7a865a47118ceccf14ff44d5a82e109ed)
2025-04-18 15:50:07.939 DEBUG            pid-9220          A        #14 pc 000000000058ef84  /data/app/~~JvgCV0-DB5RQK8W6lSPdPw==/com.example-UV3hsa0g-763pMxGoZMWVw==/lib/x86_64/libpjsua2.so (pj_ioqueue_poll+1444) (BuildId: 0c29c5e7a865a47118ceccf14ff44d5a82e109ed)
2025-04-18 15:50:07.939 DEBUG            pid-9220          A        #15 pc 00000000004380ba  /data/app/~~JvgCV0-DB5RQK8W6lSPdPw==/com.example-UV3hsa0g-763pMxGoZMWVw==/lib/x86_64/libpjsua2.so (worker_proc+90) (BuildId: 0c29c5e7a865a47118ceccf14ff44d5a82e109ed)
2025-04-18 15:50:07.939 DEBUG            pid-9220          A        #16 pc 0000000000588d96  /data/app/~~JvgCV0-DB5RQK8W6lSPdPw==/com.example-UV3hsa0g-763pMxGoZMWVw==/lib/x86_64/libpjsua2.so (thread_main+182) (BuildId: 0c29c5e7a865a47118ceccf14ff44d5a82e109ed)
---------------------------- PROCESS ENDED (8025) ----------------------------
```

### PR DESCRIPTION
**Pull request by sauwming**
To fix #4404.

As reported in https://github.com/pjsip/pjproject/issues/4404, PJSIP will crash when using Android video mediacodec and remote sends a video with resolution higher than supported.

Although the issue was caused by the remote sending video with resolution higher than signalled, PJSIP shouldn't crash. The crash is caused due to lack of checking of the frame buffer size that's supposed to hold the decoded frame.

### CODE REVIEW

**Review by nanangizz — APPROVED** [review]

File: pjmedia/src/pjmedia-codec/and_vid_mediacodec.cpp [hunk 1]
```diff
@@ -1490,12 +1490,16 @@ static pj_status_t and_media_decode(pjmedia_vid_codec *codec,
         PJ_LOG(4,(THIS_FILE, "Decoder getOutputBuffer failed"));
         return status;
     }
-    len = write_yuv((pj_uint8_t *)output->buf,
-                    output->size,
-                    output_buf,
-                    and_media_data->dec_stride_len,
-                    and_media_data->prm->dec_fmt.det.vid.size.w,
-                    and_media_data->prm->dec_fmt.det.vid.size.h);
+    if (output->size >= and_media_data->prm->dec_fmt.det.vid.size.w *
```
Comment (wxiaoguang) [inline pjmedia/src/pjmedia-codec/and_vid_mediacodec.cpp:1493]: I think this check doesn't fix the overflow. Because `write_yuv` already checks `if (output->size < w * h * 3 / 2)`

I proposed a new fix:  Fix android video codec overflow #4617
