### PR TITLE
Fixed ioq winnt build failure

### LINKED ISSUE #2576: windows ioqueue use iocp (ioqueue_winnt.c) build fail
**Describe the bug**
use visual studio 2015, open project,  select ioqueue_winnt.c replace ioqueue_select.c,   
build fail, no function ' pj_ioqueue_register_sock2'

iocp file (ioqueue_winnt.c) not sync update, please check it.

### LINKED ISSUE #3291: ioqueue_winnt.c is outdated and can't be linked
### Describe the bug

ioqueue_winnt.c is outdated and can't be linked because of lack new API like pj_ioqueue_register_sock2. By default Windows builds use ioqueue_select.c but this implementation has limits. ioqueue_winnt.c has no limitations but just outdated.

### Steps to reproduce

enable ioqueue_winnt.c compilation and build

### PJSIP version

2.11.1

### Context

Windows builds

### Log, call stack, etc

```shell
1>pjlib-util-i386-Win32-vc14-Release-Static.lib(resolver.obj) : error LNK2001: unresolved external symbol _pj_ioqueue_register_sock2
```

### PR DESCRIPTION
**Pull request by sauwming**
****IMPORTANT**:
Although ioq-winnt (IOCP) backend can now build successfully and pass the unit tests, it lacks the group lock functionality so users should only use it for experimental testing purposes and should NOT use it for actual development and production.

To fix #3291 and close #2576.

### CODE REVIEW

File: pjlib/src/pj/ioqueue_winnt.c [hunk 1]
```diff
@@ -586,6 +611,12 @@ PJ_DEF(pj_status_t) pj_ioqueue_register_sock( pj_pool_t *pool,
         return PJ_RETURN_OS_ERROR(GetLastError());
     }
 
+    /* Group lock */
+    rec->grp_lock = grp_lock;
+    if (rec->grp_lock) {
+        pj_grp_lock_add_ref_dbg(rec->grp_lock, "ioqueue", 0);
```
Comment (nanangizz) [inline pjlib/src/pj/ioqueue_winnt.c:617]: - there should be the `pj_grp_lock_dec_ref()` pair?
- as in other ioqueue, the group lock `add/dec_ref()` is invoked surrounding event callbacks to prevent premature destroy/unregistration by other thread while the app is inside the callback?

Comment (sauwming) [reply pjlib/src/pj/ioqueue_winnt.c]: Ah, right. Integrating group lock will be a much more complicated task.

Just a bit of background, the group lock introduction was done in #1616 dated Feb 2013 for release 2.1 and was integrated into ioq select and even (the then-experimental) epoll backend. Ioq-winnt (IOCP) was notably missing and not sure whether it was simply overlooked or if there were some implementation challenges during the integration. But the obvious thing is that IOCP hasn't been working for more than a decade and there didn't seem to be much interest (?) either.

So for now I suggest the PR is just to fix the build failure. If more users start using this backend again, we may consider revisiting the group lock integration.

**Review by nanangizz — APPROVED** [review]
