### PR TITLE
Fixed race condition between media event callback and stopping video

### LINKED ISSUE #2513: Crashing On IOS Assertion failed: (vid_conf && src_slot<vid_conf->opt.max_slot_cnt && sink_slot<vid_conf->opt.max_slot_cnt), function pjmedia_vid_conf_disconnect_port, file ../src/pjmedia/vid_conf.c, line 595.
**Describe the bug**

Crashing On IOS 13.5.1, iPhone XS Max Sometimes on Video calls. 

2020-08-18 21:53:34.437433-0700 community[7350:1654766] PushRegistryManagerDelegate {
    aps =     {
        alert = "Incoming Call";
    };
    "caller_contact_name" = "My Deskphone";
    from = 505;
    "linked_uuid" = "cc7a8081-912c-4059-9712-721a158198d8";
    server = "freeswitch-13";
    slot = "cc7a8081-912c-4059-9712-721a158198d8";
}
21:53:35.363         sip_endpoint.c  Processing incoming message: Request msg INVITE/cseq=1 (rdata0x10881c108)
21:53:35.363           pjsua_core.c  .RX 1114 bytes Request msg INVITE/cseq=1 (rdata0x10881c108) from TCP 72.1.47.164:5060:
INVITE sip:226586@192.168.1.100:53654;transport=TCP;ob SIP/2.0

Via: SIP/2.0/TCP 72.1.47.164:5060;branch=z9hG4bK1sansay681507rdb22

Record-Route: <sip:sansay681507rdb22@72.1.47.164:5060;lr;transport=tcp>

To: <sip:226586@192.168.1.100>

From: "My Deskphone" <sip:505@72.1.47.164>;tag=sansay681507rdb22

Call-ID: c7672e05-5c7a-1239-8b91-f04da20b409a

CSeq: 1 INVITE

Contact: <sip:505@72.1.47.164:5060>

Supported: timer,replaces,path

Session-Expires: 600;refresher=uas

Min-SE: 90

Allow: INVITE, ACK, BYE, CANCEL, OPTIONS, MESSAGE, INFO, UPDATE, REGISTER, REFER, NOTIFY, PUBLISH, SUBSCRIBE

X-Linked-UUID: cc7a8081-912c-4059-9712-721a158198d8

Content-Type: application/sdp

Content-Length: 414

v=0

o=Sansay-VSXi 188 1 IN IP4 72.1.47.164

s=Session Controller

c=IN IP4 72.1.47.164

t=0 0

m=audio 14086 RTP/AVP 9 0 8 101

a=rtpmap:9 G722/8000

a=rtpmap:0 PCMU/8000

a=rtpmap:8 PCMA/8000

a=rtpmap:101 telephone-event/8000

a=fmtp:101 0-16

a=ptime:20

m=video 14090 RTP/AVP 102

b=AS:1024

a=rtpmap:102 H264/90000

a=rtcp-fb:102 ccm fir

a=rtcp-fb:102 ccm tmmbr

a=rtcp-fb:102 nack

a=rtcp-fb:102 nack pli

--end msg--
21:53:35.363           pjsua_call.c  .Incoming Request msg INVITE/cseq=1 (rdata0x10881c108)
21:53:35.363         tsx0x10703cea8  ...Transaction created for Request msg INVITE/cseq=1 (rdata0x10881c108)
21:53:35.363         tsx0x10703cea8  ..Incoming Request msg INVITE/cseq=1 (rdata0x10881c108) in state Null
21:53:35.363         tsx0x10703cea8  ...State changed from Null to Trying, event=RX_MSG
21:53:35.363         dlg0x10703c6a8  ....Transaction tsx0x10703cea8 state changed to Trying
21:53:35.363         dlg0x10703c6a8  ..UAS dialog created
21:53:35.363         dlg0x10703c6a8  ..Module mod-invite added as dialog usage, data=0x10702d828
21:53:35.363         dlg0x10703c6a8  ...Session count inc to 3 by mod-invite
21:53:35.364         inv0x10703c6a8  ..UAS invite session created for dialog dlg0x10703c6a8
21:53:35.364         dlg0x10703c6a8  ...Session count inc to 3 by mod-pjsua
21:53:35.364          pjsua_media.c  ..Call 2: initializing media..
21:53:35.429          pjsua_media.c  ...RTP socket reachable at 99.121.252.173:4008
21:53:35.429          pjsua_media.c  ...RTCP socket reachable at 99.121.252.173:4009
21:53:35.429        srtp0x10782ee00  ...SRTP keying SDES created
21:53:35.491          pjsua_media.c  ...RTP socket reachable at 99.121.252.173:4010
21:53:35.491          pjsua_media.c  ...RTCP socket reachable at 99.121.252.173:4011
21:53:35.491        srtp0x108016400  ...SRTP keying SDES created
21:53:35.491          pjsua_media.c  ...Media index 0 selected for audio call 2
21:53:35.491          pjsua_media.c  ...Call 2: media transport initialization complete: Success
2020-08-18 21:53:35.491867-0700 community[7350:1655148] answer_with_ringing CC7A8081-912C-4059-9712-721A158198D8
21:53:35.492           pjsua_call.c  ...Answering call 2: code=183
21:53:35.492           pjsua_call.c  ....Pending answering call 2 upon completion of media transport
21:53:35.492         dlg0x10703c6a8  ...Session count dec to 3 by mod-pjsua
21:53:35.494           pjsua_call.c  ..Call 2: remote NAT type is 0 (Unknown)
21:53:35.494               endpoint  ...Response msg 100/INVITE/cseq=1 (tdta0x10703b6a8) created
21:53:35.494         dlg0x10703c6a8  ...Initial answer Response msg 100/INVITE/cseq=1 (tdta0x10703b6a8)
21:53:35.494         inv0x10703c6a8  ...Sending Response msg 100/INVITE/cseq=1 (tdta0x10703b6a8)
21:53:35.494         dlg0x10703c6a8  ....Sending Response msg 100/INVITE/cseq=1 (tdta0x10703b6a8)
21:53:35.494         tsx0x10703cea8  ....Sending Response msg 100/INVITE/cseq=1 (tdta0x10703b6a8) in state Trying
21:53:35.494           pjsua_core.c  .....TX 365 bytes Response msg 100/INVITE/cseq=1 (tdta0x10703b6a8) to TCP 72.1.47.164:5060:
SIP/2.0 100 Trying

Via: SIP/2.0/TCP 72.1.47.164:5060;received=72.1.47.164;branch=z9hG4bK1sansay681507rdb22

Record-Route: <sip:sansay681507rdb22@72.1.47.164:5060;transport=tcp;lr>

Call-ID: c7672e05-5c7a-1239-8b91-f04da20b409a

From: "My Deskphone" <sip:505@72.1.47.164>;tag=sansay681507rdb22

To: <sip:226586@192.168.1.100>

CSeq: 1 INVITE

Content-Length:  0

--end msg--
21:53:35.494         tsx0x10703cea8  .....State changed from Trying to Proceeding, event=TX_MSG
21:53:35.494         dlg0x10703c6a8  ......Transaction tsx0x10703cea8 state changed to Proceeding
21:53:35.495           pjsua_call.c  ..Answering call 2: code=183
21:53:35.495        sip_transport.c  ....Tx data Response msg 100/INVITE/cseq=1 (tdta0x108833ca8) cloned
21:53:35.495         inv0x10703c6a8  ....SDP negotiation done: Success
21:53:35.495           pjsua_call.c  .....Call 2: remote NAT type is 0 (Unknown)
21:53:35.495          pjsua_media.c  .....Call 2: updating media..
21:53:35.496          pjsua_media.c  .......Media stream call02:0 is destroyed
21:53:35.496            pjsua_aud.c  ......Audio channel update..
21:53:35.496        strm0x107831a28  .......VAD temporarily disabled
21:53:35.496                  rtp.c  .......pjmedia_rtp_session_init: ses=0x107834918, default_pt=9, ssrc=0x3c4ff77b
21:53:35.496                  rtp.c  .......pjmedia_rtp_session_init2: ses=0x107834918, seq=5007, ts=0, peer_ssrc=0
21:53:35.496                  rtp.c  .......pjmedia_rtp_session_init: ses=0x107835010, default_pt=9, ssrc=0x3c4ff77b
21:53:35.496                  rtp.c  .......pjmedia_rtp_session_init2: ses=0x107835010, seq=4668, ts=0, peer_ssrc=0
21:53:35.496         udp0x103c0fe50  .......SO_RCVBUF set to 196724
21:53:35.496         udp0x103c0fe50  .......SO_SNDBUF set to 65536
21:53:35.496               stream.c  .......Stream strm0x107831a28 created
21:53:35.496        strm0x107831a28  .......Encoder stream started
21:53:35.496        strm0x107831a28  .......Decoder stream started
21:53:35.497          pjsua_media.c  ......Audio updated, stream #0: G722 (sendrecv)
21:53:35.497          pjsua_media.c  .......Media stream call02:1 is destroyed
21:53:35.497            pjsua_vid.c  ......Video channel update..
21:53:35.497          vid_toolbox.m  .......Opening codec..
21:53:35.530                  rtp.c  .......pjmedia_rtp_session_init: ses=0x10803252c, default_pt=102, ssrc=0x2600cb2c
21:53:35.530                  rtp.c  .......pjmedia_rtp_session_init2: ses=0x10803252c, seq=22751, ts=0, peer_ssrc=0
21:53:35.530      vstdec0x108031628  .......Decoding channel created 1280x720 I420<-H264 30/1(~30)fps
21:53:35.530                  rtp.c  .......pjmedia_rtp_session_init: ses=0x10802d13c, default_pt=102, ssrc=0x2600cb2c
21:53:35.530                  rtp.c  .......pjmedia_rtp_session_init2: ses=0x10802d13c, seq=14885, ts=0, peer_ssrc=0
21:53:35.530      vstenc0x108031628  .......Encoding channel created 176x144 I420->H264 15/1(~15)fps
21:53:35.530         udp0x103d19f80  .......SO_RCVBUF set to 196724
21:53:35.530         udp0x103d19f80  .......SO_SNDBUF set to 65536
21:53:35.530       vstrm0x108031628  .......Send RTCP-FB generic NACK
21:53:35.531       vstrm0x108031628  .......Send RTCP-FB PLI
21:53:35.531           vid_stream.c  .......Video stream vstrm0x108031628 created
21:53:35.531      vstenc0x108031628  .......Encoder stream started
21:53:35.531      vstdec0x108031628  .......Decoder stream started
21:53:35.531            pjsua_vid.c  .......Setting up RX..
21:53:35.531            pjsua_vid.c  ........Creating video window: type=stream, cap_id=-1, rend_id=0
21:53:35.531             vid_port.c  .........Opening device OpenGL renderer [OpenGL] for render: format=I420, size=1280x720 @30:1 fps
21:53:35.542       ios_opengl_dev.c  .........iOS OpenGL ES renderer successfully created
21:53:35.542             vid_port.c  .........Device OpenGL renderer [OpenGL] opened: format=BGRA, size=1280x720 @30:1 fps
21:53:35.543             vid_conf.c  .........Added port 0 (OpenGL renderer)
21:53:35.543            pjsua_vid.c  .........stream window id 0 created for cap_dev=-1 rend_dev=0
21:53:35.543            pjsua_vid.c  .........Window 0 created
21:53:35.544             vid_conf.c  ........Added port 1 (vstdec0x108031628)
21:53:35.544             vid_conf.c  ........Updating render state for port id 0 (1 sources)..
21:53:35.544             vid_conf.c  ........This port only has single source with matched format & size, no conversion needed
21:53:35.544             vid_conf.c  ........Port 1 (vstdec0x108031628) transmitting to port 0 (OpenGL renderer)
21:53:35.544       ios_opengl_dev.c  ........Starting ios opengl stream
21:53:35.544            pjsua_vid.c  .......Setting up TX..
21:53:35.544             vid_conf.c  ........Added port 2 (vstenc0x108031628)
21:53:35.544            pjsua_vid.c  ........Creating video window: type=preview, cap_id=2, rend_id=0
21:53:35.544             vid_port.c  .........Opening device Colorbar generator [Colorbar] for capture: format=I420, size=176x144 @15:1 fps
21:53:35.544             vid_port.c  .........Device Colorbar generator [Colorbar] opened: format=I420, size=352x288 @15:1 fps
21:53:35.544             vid_conf.c  .........Added port 3 (Colorbar generator)
21:53:35.544             vid_port.c  .........Opening device OpenGL renderer [OpenGL] for render: format=I420, size=176x144 @15:1 fps
21:53:35.548       ios_opengl_dev.c  .........iOS OpenGL ES renderer successfully created
21:53:35.548             vid_port.c  .........Device OpenGL renderer [OpenGL] opened: format=BGRA, size=176x144 @15:1 fps
21:53:35.548             vid_conf.c  .........Added port 4 (OpenGL renderer)
21:53:35.549            pjsua_vid.c  .........preview window id 1 created for cap_dev=2 rend_dev=0
21:53:35.549            pjsua_vid.c  .........Window 1 created
21:53:35.549             vid_conf.c  ........Updating render state for port id 2 (1 sources)..
21:53:35.549             vid_conf.c  ........This port only has single source with matched format & size, no conversion needed
21:53:35.549             vid_conf.c  ........Port 3 (Colorbar generator) transmitting to port 2 (vstenc0x108031628)
21:53:35.549         colorbar_dev.c  ........Starting cbar video stream
21:53:35.549            pjsua_vid.c  ........Call 2 media 1: video capture set up with dev 2, wid=1
21:53:35.549          pjsua_media.c  ......Video updated, stream #1: H264 (sendrecv)
21:53:35.549            pjsua_aud.c  .....Conf connect: 1 --> 0
21:53:35.549           conference.c  ......Port 1 (sip:505@72.1.47.164) transmitting to port 0 (iPhone IO device)
21:53:35.549            pjsua_aud.c  .....Conf connect: 0 --> 1
21:53:35.549           conference.c  ......Port 0 (iPhone IO device) transmitting to port 1 (sip:505@72.1.47.164)
21:53:35.550         inv0x10703c6a8  ....Sending Response msg 183/INVITE/cseq=1 (tdta0x108833ca8)
21:53:35.550         dlg0x10703c6a8  .....Sending Response msg 183/INVITE/cseq=1 (tdta0x108833ca8)
21:53:35.550         tsx0x10703cea8  .....Sending Response msg 183/INVITE/cseq=1 (tdta0x108833ca8) in state Proceeding
21:53:35.550        tdta0x10703b6a8  ......Destroying txdata Response msg 100/INVITE/cseq=1 (tdta0x10703b6a8)
21:53:35.550           pjsua_core.c  ......TX 1164 bytes Response msg 183/INVITE/cseq=1 (tdta0x108833ca8) to TCP 72.1.47.164:5060:
SIP/2.0 183 Session Progress

Via: SIP/2.0/TCP 72.1.47.164:5060;received=72.1.47.164;branch=z9hG4bK1sansay681507rdb22

Record-Route: <sip:sansay681507rdb22@72.1.47.164:5060;transport=tcp;lr>

Call-ID: c7672e05-5c7a-1239-8b91-f04da20b409a

From: "My Deskphone" <sip:505@72.1.47.164>;tag=sansay681507rdb22

To: <sip:226586@192.168.1.100>;tag=26trBc-XGeDy91n7jG4RZiOgY6FTQmdC

CSeq: 1 INVITE

Contact: <sip:226586@192.168.1.100:53654;transport=TCP;ob>

Allow: PRACK, INVITE, ACK, BYE, CANCEL, UPDATE, INFO, SUBSCRIBE, NOTIFY, REFER, MESSAGE, OPTIONS

Content-Type: application/sdp

Content-Length:   560

v=0

o=- 3806801615 3806801616 IN IP4 99.121.252.173

s=pjmedia

b=AS:386

t=0 0

a=X-nat:1

m=audio 4008 RTP/AVP 9 101

c=IN IP4 99.121.252.173

b=TIAS:96000

a=rtcp:4009 IN IP4 99.121.252.173

a=sendrecv

a=rtpmap:9 G722/8000

a=ssrc:1011873659 cname:66ca9dc5003c253c

a=rtpmap:101 telephone-event/8000

a=fmtp:101 0-16

m=video 4010 RTP/AVP 102

c=IN IP4 99.121.252.173

b=TIAS:256000

a=rtcp:4011 IN IP4 99.121.252.173

a=sendrecv

a=ssrc:637586220 cname:66ca9dc5003c253c

a=rtpmap:102 H264/90000

a=fmtp:102 profile-level-id=42000a; packetization-mode=0

--end msg--
21:53:35.550         tsx0x10703cea8  ......State changed from Proceeding to Proceeding, event=TX_MSG
21:53:35.550         dlg0x10703c6a8  .......Transaction tsx0x10703cea8 state changed to Proceeding
21:53:35.562      vstenc0x108031628 !Keyframe generated
21:53:36.177           pjsua_call.c !Answering call 2: code=200
21:53:36.177        sip_transport.c  ..Tx data Response msg 183/INVITE/cseq=1 (tdta0x108831ca8) cloned
21:53:36.177         inv0x10703c6a8  ..Sending Response msg 200/INVITE/cseq=1 (tdta0x108831ca8)
21:53:36.177         dlg0x10703c6a8  ...Sending Response msg 200/INVITE/cseq=1 (tdta0x108831ca8)
21:53:36.177         tsx0x10703cea8  ...Sending Response msg 200/INVITE/cseq=1 (tdta0x108831ca8) in state Proceeding
21:53:36.177        tdta0x108833ca8  ....Destroying txdata Response msg 183/INVITE/cseq=1 (tdta0x108833ca8)
21:53:36.177           pjsua_core.c  ....TX 1234 bytes Response msg 200/INVITE/cseq=1 (tdta0x108831ca8) to TCP 72.1.47.164:5060:
SIP/2.0 200 OK

Via: SIP/2.0/TCP 72.1.47.164:5060;received=72.1.47.164;branch=z9hG4bK1sansay681507rdb22

Record-Route: <sip:sansay681507rdb22@72.1.47.164:5060;transport=tcp;lr>

Call-ID: c7672e05-5c7a-1239-8b91-f04da20b409a

From: "My Deskphone" <sip:505@72.1.47.164>;tag=sansay681507rdb22

To: <sip:226586@192.168.1.100>;tag=26trBc-XGeDy91n7jG4RZiOgY6FTQmdC

CSeq: 1 INVITE

Allow: PRACK, INVITE, ACK, BYE, CANCEL, UPDATE, INFO, SUBSCRIBE, NOTIFY, REFER, MESSAGE, OPTIONS

Contact: <sip:226586@192.168.1.100:53654;transport=TCP;ob>

Supported: replaces, 100rel, timer, norefersub

Session-Expires: 600;refresher=uas

Content-Type: application/sdp

Content-Length:   560

v=0

o=- 3806801615 3806801616 IN IP4 99.121.252.173

s=pjmedia

b=AS:386

t=0 0

a=X-nat:1

m=audio 4008 RTP/AVP 9 101

c=IN IP4 99.121.252.173

b=TIAS:96000

a=rtcp:4009 IN IP4 99.121.252.173

a=sendrecv

a=rtpmap:9 G722/8000

a=ssrc:1011873659 cname:66ca9dc5003c253c

a=rtpmap:101 telephone-event/8000

a=fmtp:101 0-16

m=video 4010 RTP/AVP 102

c=IN IP4 99.121.252.173

b=TIAS:256000

a=rtcp:4011 IN IP4 99.121.252.173

a=sendrecv

a=ssrc:637586220 cname:66ca9dc5003c253c

a=rtpmap:102 H264/90000

a=fmtp:102 profile-level-id=42000a; packetization-mode=0

--end msg--
21:53:36.179         tsx0x10703cea8  ....State changed from Proceeding to Completed, event=TX_MSG
21:53:36.179         dlg0x10703c6a8  .....Transaction tsx0x10703cea8 state changed to Completed
21:53:36.208         sip_endpoint.c !Processing incoming message: Request msg ACK/cseq=1 (rdata0x10881c108)
21:53:36.208           pjsua_core.c  .RX 367 bytes Request msg ACK/cseq=1 (rdata0x10881c108) from TCP 72.1.47.164:5060:
ACK sip:226586@192.168.1.100:53654;transport=TCP;ob SIP/2.0

Via: SIP/2.0/TCP 72.1.47.164:5060;branch=z9hG4bK1sansay681507rdb22-200

To: <sip:226586@192.168.1.100>;tag=26trBc-XGeDy91n7jG4RZiOgY6FTQmdC

From: "My Deskphone" <sip:505@72.1.47.164>;tag=sansay681507rdb22

Call-ID: c7672e05-5c7a-1239-8b91-f04da20b409a

CSeq: 1 ACK

Max-Forwards: 70

Content-Length: 0

--end msg--
21:53:36.208         dlg0x10703c6a8  .Received Request msg ACK/cseq=1 (rdata0x10881c108)
21:53:36.208         tsx0x10703cea8  ..Request to terminate transaction
21:53:36.208         tsx0x10703cea8  ...State changed from Completed to Terminated, event=USER
21:53:36.208         dlg0x10703c6a8  ....Transaction tsx0x10703cea8 state changed to Terminated
21:53:36.209         tsx0x10703cea8  Timeout timer event
21:53:36.209         tsx0x10703cea8  .State changed from Terminated to Destroyed, event=TIMER
CALL STATE CHANGED HANDER == SIP_CALL_STATE(rawValue: 3)
21:53:36.209        tdta0x108831ca8  ..Destroying txdata Response msg 200/INVITE/cseq=1 (tdta0x108831ca8)
21:53:36.209         tsx0x10703cea8  Transaction destroyed!
21:53:36.262      vstdec0x108031628 !RTP status: badpt=0, badssrc=0, dup=0, outorder=0, probation=-1, restart=0
21:53:36.524          vid_toolbox.m  Decode couldn't produce picture, input nframes=35, concatenated size=39574 bytes
21:53:36.532          pjsua_media.c !Call 2: Media 1: Received media event, type=IFRM, src=0x103d09288, epub=0x1080324a8
21:53:36.532          pjsua_media.c  Call 2: Media 1: Received media event, type=IFRM, src=0x103d09288, epub=0x103c08a68
+++++++++++++PJMEDIA_EVENT_MEDIA 1297237577
+++++++++++++PJMEDIA_EVENT_KEYFRAME_MISSING
+++++++++++++PJMEDIA_EVENT_MEDIA 1297237577
+++++++++++++PJMEDIA_EVENT_KEYFRAME_MISSING
21:53:36.599            pjsua_aud.c !Set sound device: capture=-1, playback=-2
21:53:36.599            pjsua_aud.c  .Opening sound device (speaker + mic) PCM@16000/1/20ms
21:53:36.599        coreaudio_dev.c  ..Using VoiceProcessingIO audio unit
21:53:36.965        coreaudio_dev.c  ..core audio stream started
21:53:36.981        coreaudio_dev.c !Recorder thread started, (341 frames)
21:53:36.981         os_core_unix.c  Info: possibly re-registering existing thread
21:53:36.981        coreaudio_dev.c !Player thread started, (341 frames)
21:53:36.981        strm0x107831a28  Resetting jitter buffer in stream playback start
21:53:36.981        strm0x107831a28  Start talksprut..
21:53:36.981           Master/sound  Underflow, buf_cnt=0, will generate 1 frame
21:53:36.982        strm0x107831a28  Jitter buffer empty (prefetch=0)
21:53:37.000            pjsua_aud.c !Set sound device: capture=-1, playback=-2
21:53:37.000            pjsua_aud.c  .No changes in capture and playback devices
21:53:37.006           pjsua_call.c  Sending re-INVITE on call 2
21:53:37.006          pjsua_media.c  .Call 2: re-initializing media..
21:53:37.006          pjsua_media.c  ..Media index 0 selected for audio call 2
21:53:37.006          pjsua_media.c  ..Call 2: media transport initialization complete: Success
21:53:37.006               endpoint  ..Request msg INVITE/cseq=7678 (tdta0x1080776a8) created.
21:53:37.006         inv0x10703c6a8  ..Sending Request msg INVITE/cseq=7678 (tdta0x1080776a8)
21:53:37.006         dlg0x10703c6a8  ...Sending Request msg INVITE/cseq=7678 (tdta0x1080776a8)
21:53:37.006         tsx0x10807b6a8  ....Transaction created for Request msg INVITE/cseq=7677 (tdta0x1080776a8)
21:53:37.006         tsx0x10807b6a8  ...Sending Request msg INVITE/cseq=7677 (tdta0x1080776a8) in state Null
21:53:37.006          sip_resolve.c  ....Target '72.1.47.164:5060' type=TCP resolved to '72.1.47.164:5060' type=TCP (TCP transport)
21:53:37.006           pjsua_core.c  ....TX 1750 bytes Request msg INVITE/cseq=7677 (tdta0x1080776a8) to TCP 72.1.47.164:5060:
INVITE sip:505@72.1.47.164:5060 SIP/2.0

Via: SIP/2.0/TCP 99.121.252.173:53654;rport;branch=z9hG4bKPjmI80plY2e4zA1PPLqYZXFfhMU0xeJTKQ;alias

Max-Forwards: 70

From: <sip:226586@192.168.1.100>;tag=26trBc-XGeDy91n7jG4RZiOgY6FTQmdC

To: "My Deskphone" <sip:505@72.1.47.164>;tag=sansay681507rdb22

Contact: <sip:226586@192.168.1.100:53654;transport=TCP;ob>

Call-ID: c7672e05-5c7a-1239-8b91-f04da20b409a

CSeq: 7677 INVITE

Route: <sip:sansay681507rdb22@72.1.47.164:5060;transport=tcp;lr>

Allow: PRACK, INVITE, ACK, BYE, CANCEL, UPDATE, INFO, SUBSCRIBE, NOTIFY, REFER, MESSAGE, OPTIONS

Supported: replaces, 100rel, timer, norefersub

Session-Expires: 600;refresher=uac

Min-SE: 90

User-Agent: myq-mobileoffice

Content-Type: application/sdp

Content-Length:   984

v=0

o=- 3806801615 3806801617 IN IP4 99.121.252.173

s=pjmedia

b=AS:386

t=0 0

a=X-nat:1

m=audio 4008 RTP/AVP 96 9 8 0 3 97 98 99 100 120 121 122 123

c=IN IP4 99.121.252.173

b=TIAS:96000

a=rtcp:4009 IN IP4 99.121.252.173

a=sendrecv

a=rtpmap:96 opus/48000/2

a=fmtp:96 useinbandfec=1

a=rtpmap:9 G722/8000

a=rtpmap:8 PCMA/8000

a=rtpmap:0 PCMU/8000

a=rtpmap:3 GSM/8000

a=rtpmap:97 iLBC/8000

a=fmtp:97 mode=30

a=rtpmap:98 speex/32000

a=rtpmap:99 speex/16000

a=rtpmap:100 speex/8000

a=rtpmap:120 telephone-event/48000

a=fmtp:120 0-16

a=rtpmap:121 telephone-event/8000

a=fmtp:121 0-16

a=rtpmap:122 telephone-event/32000

a=fmtp:122 0-16

a=rtpmap:123 telephone-event/16000

a=fmtp:123 0-16

a=ssrc:1011873659 cname:66ca9dc5003c253c

m=video 4010 RTP/AVP 97

c=IN IP4 99.121.252.173

b=TIAS:256000

a=rtcp:4011 IN IP4 99.121.252.173

a=sendrecv

a=rtpmap:97 H264/90000

a=fmtp:97 profile-level-id=42e01e; packetization-mode=1

a=ssrc:637586220 cname:66ca9dc5003c253c

--end msg--
21:53:37.016         tsx0x10807b6a8 !....State changed from Null to Calling, event=TX_MSG
21:53:37.019         dlg0x10703c6a8  .....Transaction tsx0x10807b6a8 state changed to Calling
21:53:37.007        strm0x107831a28 !RTP status: badpt=0, badssrc=0, dup=0, outorder=0, probation=-1, restart=0
21:53:37.024      vstenc0x108031628 !Forcing encoder to generate keyframe
21:53:37.025        strm0x107831a28 !Jitter buffer starts returning normal frames (after 2 empty/lost)
21:53:37.028      vstenc0x108031628 !Keyframe generated
21:53:37.028               stream.c !G722 codec used, remote samples per frame detected = 80
21:53:37.039       vstrm0x108031628 !Sending RTCP-FB PLI packet
21:53:37.042         sip_endpoint.c !Processing incoming message: Response msg 100/INVITE/cseq=7677 (rdata0x10881c108)
21:53:37.042           pjsua_core.c  .RX 348 bytes Response msg 100/INVITE/cseq=7677 (rdata0x10881c108) from TCP 72.1.47.164:5060:
SIP/2.0 100 Trying

Via: SIP/2.0/TCP 99.121.252.173:53654;rport=53654;branch=z9hG4bKPjmI80plY2e4zA1PPLqYZXFfhMU0xeJTKQ;alias

To: "My Deskphone" <sip:505@72.1.47.164>;tag=sansay681507rdb22

From: <sip:226586@192.168.1.100>;tag=26trBc-XGeDy91n7jG4RZiOgY6FTQmdC

Call-ID: c7672e05-5c7a-1239-8b91-f04da20b409a

CSeq: 7677 INVITE

Content-Length: 0

--end msg--
21:53:37.042         tsx0x10807b6a8  .Incoming Response msg 100/INVITE/cseq=7677 (rdata0x10881c108) in state Calling
21:53:37.042         tsx0x10807b6a8  ..State changed from Calling to Proceeding, event=RX_MSG
21:53:37.042         dlg0x10703c6a8  ...Received Response msg 100/INVITE/cseq=7677 (rdata0x10881c108)
21:53:37.042         dlg0x10703c6a8  ...Transaction tsx0x10807b6a8 state changed to Proceeding
21:53:37.082         sip_endpoint.c  Processing incoming message: Response msg 200/INVITE/cseq=7677 (rdata0x10881c108)
21:53:37.082           pjsua_core.c  .RX 1107 bytes Response msg 200/INVITE/cseq=7677 (rdata0x10881c108) from TCP 72.1.47.164:5060:
SIP/2.0 200 OK

Via: SIP/2.0/TCP 99.121.252.173:53654;rport=53654;branch=z9hG4bKPjmI80plY2e4zA1PPLqYZXFfhMU0xeJTKQ;alias

Record-Route: <sip:sansay681507rdb22@72.1.47.164:5060;lr;transport=tcp>

To: "My Deskphone" <sip:505@72.1.47.164>;tag=sansay681507rdb22

From: <sip:226586@192.168.1.100>;tag=26trBc-XGeDy91n7jG4RZiOgY6FTQmdC

Call-ID: c7672e05-5c7a-1239-8b91-f04da20b409a

CSeq: 7677 INVITE

Require: timer

Session-Expires: 600;refresher=uac

Supported: timer,replaces,path

User-Agent: Phone.com Host:freeswitch-13

Accept: application/sdp

Allow: INVITE, ACK, BYE, CANCEL, OPTIONS, MESSAGE, INFO, UPDATE, REGISTER, REFER, NOTIFY, PUBLISH, SUBSCRIBE

Content-Disposition: session

Contact: <sip:505@72.1.47.164:5060>

Content-Type: application/sdp

Content-Length: 329

v=0

o=Sansay-VSXi 188 2 IN IP4 72.1.47.164

s=Session Controller

c=IN IP4 72.1.47.164

t=0 0

m=audio 14086 RTP/AVP 9 121

a=rtpmap:9 G722/8000

a=rtpmap:121 telephone-event/8000

a=fmtp:121 0-16

a=ptime:20

m=video 14090 RTP/AVP 97

b=AS:1024

a=rtpmap:97 H264/90000

a=fmtp:97 profile-level-id=42e01e; packetization-mode=1

--end msg--
21:53:37.082         tsx0x10807b6a8  .Incoming Response msg 200/INVITE/cseq=7677 (rdata0x10881c108) in state Proceeding
21:53:37.082         tsx0x10807b6a8  ..State changed from Proceeding to Terminated, event=RX_MSG
21:53:37.082         dlg0x10703c6a8  ...Received Response msg 200/INVITE/cseq=7677 (rdata0x10881c108)
21:53:37.082         dlg0x10703c6a8  ...Transaction tsx0x10807b6a8 state changed to Terminated
21:53:37.082         inv0x10703c6a8  ....Got SDP answer in Response msg 200/INVITE/cseq=7677 (rdata0x10881c108)
21:53:37.082         inv0x10703c6a8  ....SDP negotiation done: Success
21:53:37.082           pjsua_call.c  .....Call 2: remote NAT type is 0 (Unknown)
21:53:37.082          pjsua_media.c  .....Call 2: updating media..
21:53:37.083        strm0x107831a28  .......JB summary:
  size=2/eff=2 prefetch=0 level=0
  delay (min/max/avg/dev)=20/40/33/9 ms
  burst (min/max/avg/dev)=0/0/0/0 frames
  lost=0 discard=0 empty=2
21:53:37.083          pjsua_media.c  .......Media stream call02:0 is destroyed
21:53:37.083            pjsua_aud.c  ......Audio channel update..
21:53:37.083        strm0x108832c28  .......VAD temporarily disabled
21:53:37.083                  rtp.c  .......pjmedia_rtp_session_init: ses=0x108835318, default_pt=9, ssrc=0x3c4ff77b
21:53:37.083                  rtp.c  .......pjmedia_rtp_session_init2: ses=0x108835318, seq=4674, ts=960, peer_ssrc=0
21:53:37.083                  rtp.c  .......pjmedia_rtp_session_init: ses=0x108835a10, default_pt=9, ssrc=0x3c4ff77b
21:53:37.083                  rtp.c  .......pjmedia_rtp_session_init2: ses=0x108835a10, seq=4674, ts=960, peer_ssrc=0
21:53:37.083         udp0x103c0fe50  .......SO_RCVBUF set to 196724
21:53:37.083         udp0x103c0fe50  .......SO_SNDBUF set to 65536
21:53:37.083               stream.c  .......Stream strm0x108832c28 created
21:53:37.083        strm0x108832c28  .......Encoder stream started
21:53:37.083        strm0x108832c28  .......Decoder stream started
21:53:37.083          pjsua_media.c  ......Audio updated, stream #0: G722 (sendrecv)
21:53:37.083            pjsua_vid.c  .......Stopping video stream..
21:53:37.088        strm0x108832c28 !Start talksprut..
21:53:37.096       vstrm0x108031628 !Sending RTCP-FB PLI packet
21:53:37.096      vstdec0x108031628   Decoding format changed: 1280x720 I420<- 90000/2790(~32)fps
21:53:37.097          pjsua_media.c !Call 2: Media 1: Received media event, type=FMCH, src=0x1080324a8, epub=0x1080324a8
21:53:37.104        strm0x108832c28 !RTP status: badpt=0, badssrc=0, dup=0, outorder=0, probation=-1, restart=0
21:53:37.115      vstdec0x108031628  RTP status: badpt=-1, badssrc=0, dup=0, outorder=0, probation=0, restart=0
21:53:37.115      vstdec0x108031628  Bad RTP pt 97 (expecting 102)
21:53:37.115      vstdec0x108031628  RTP status: badpt=-1, badssrc=0, dup=0, outorder=0, probation=0, restart=0
21:53:37.115      vstdec0x108031628  Bad RTP pt 97 (expecting 102)
21:53:37.117      vstdec0x108031628  RTP status: badpt=-1, badssrc=0, dup=0, outorder=0, probation=0, restart=0
21:53:37.117      vstdec0x108031628  Bad RTP pt 97 (expecting 102)
21:53:37.117      vstdec0x108031628  RTP status: badpt=-1, badssrc=0, dup=0, outorder=0, probation=0, restart=0
21:53:37.117      vstdec0x108031628  Bad RTP pt 97 (expecting 102)
21:53:37.119             vid_conf.c !........Port 3 (Colorbar generator) stop transmitting to port 2 (vstenc0x108031628)
21:53:37.119             vid_conf.c  ........Removed port 2 (vstenc0x108031628)
21:53:37.119             vid_conf.c  ........Port 1 (vstdec0x108031628) stop transmitting to port 0 (OpenGL renderer)
21:53:37.119             vid_conf.c  ........Removed port 1 (vstdec0x108031628)
21:53:37.119            pjsua_vid.c  ........Window 1: destroying..
21:53:37.119       ios_opengl_dev.c !Stopping ios opengl stream
21:53:37.119       ios_opengl_dev.c  Starting ios opengl stream
21:53:37.119          pjsua_media.c  Call 2: Media 1: Received media event, type=FMCH, src=0x1080324a8, epub=0x103c08a68
Assertion failed: (vid_conf && src_slot<vid_conf->opt.max_slot_cnt && sink_slot<vid_conf->opt.max_slot_cnt), function pjmedia_vid_conf_disconnect_port, file ../src/pjmedia/vid_conf.c, line 595.

### PR DESCRIPTION
**Pull request by sauwming**
This is a more general case of #2645 .

To avoid deadlock, we usually avoid holding locks when calling a callback. But if the callback happens at the same time with a destroy process, it can potentially cause problems as the callback may access objects being, or already, destroyed.

For the case of media event callback and video stoppage, there are a couple of problems found:
1. In pjsua callback
To call `on_call_media_event()` callback, we use a timer (to avoid deadlock):
```
   if (pjsua_var.ua_cfg.cb.on_call_media_event) {
        ...
    	pjsua_schedule_timer2(&call_med_event_cb, eve, 1);
   }
```
If there’s a race with `pjsua_vid_stop_stream()`, it can cause crash/assertion if inside the callback, user tries to access objects destroyed in `pjsua_vid_stop_stream()`, such as video window or stream.
Example:
In `pjsua_vid_stop_stream()`:
```
    /* Decrement ref count of stream video window */
    dec_vid_win(call_med->strm.v.rdr_win_id);
    call_med->strm.v.rdr_win_id = PJSUA_INVALID_ID;
```
In `on_call_media_event()`:
```
    wid = ci.media[med_idx].stream.vid.win_in;
    pjsua_vid_win_get_info(wid, &win_info);
```
One scenario to reproduce: make a video call (you can make more than one calls at the same time to increase the likelihood of the issue happening), then hangup right at the format change event (usually only about 1-2s after making the calls, just before the video is about to show up).

2. pjmedia event callback
pjmedia event callback is called without holding event manager’s lock, so even though `pjmedia_event_unsubscribe()` has been called, the callback can still be in the process of being invoked.
Example:
In `pjmedia_vid_port_destroy()` (some codes are removed for clarity):
```
   pjmedia_event_unsubscribe(NULL, &vidstream_event_cb, vp, vp->strm);
   pjmedia_vid_dev_stream_destroy(vp->strm);
   vp->strm = NULL;
        
   pjmedia_event_unsubscribe(NULL, &client_port_event_cb, vp,
                                  vp->client_port);
   pjmedia_port_destroy(vp->client_port);
   vp->client_port = NULL;
```
So when `client_port_event_cb()` is called, it’s possible `vp->strm` or `vp->client_port` has been destroyed.
The same scenario above can be used to trigger the issue.

The proposed fixes:
1. Event unsubscription can only happen when event manager is not the middle of calling a callback. This way, we can guarantee that after unsubscription completes, any subscriber's callback that is in progress has been completed and no future callbacks will be called.
2. If a callback is called using a timer, we need to either schedule it with a group lock to prevent objects being destroyed, or wait until it's completed. For this case, since the video media doesn't have its own group lock, we choose the latter approach.

Also fixes #2513.

### CODE REVIEW

File: pjmedia/src/pjmedia/event.c [hunk 1]
```diff
@@ -107,15 +108,22 @@ static pj_status_t event_mgr_distribute_events(pjmedia_event_mgr *mgr,
...
             if (status != PJ_SUCCESS && err == PJ_SUCCESS)
 	        err = status;
 
-            if (rls_lock)
+            if (rls_lock) {
+                pj_mutex_unlock(mgr->cb_mutex);
                 pj_mutex_lock(mgr->mutex);
+            }
         }
 	sub = *next_sub;
```
Comment (nanangizz) [inline pjmedia/src/pjmedia/event.c:128]: As `mgr->mutex` is released in the middle of list iteration, there is possibility that at this point the `*next_sub` is no longer valid, i.e: have unsubscribed and been removed from the list?

Comment (sauwming) [reply pjmedia/src/pjmedia/event.c:128]: I initially thought so too, but it turned out we already anticipated this. `next_sub` is actually a pointer to `mgr->th_next_sub` or `mgr->pub_next_sub`, so if the unsubscription removes this, it has to update either of those variables.

**Comment by sauwming** [comment]
`pjsua_call_hangup()` is not supposed to be called from the main/UI thread. Even now (without this patch), it will cause deadlock with any video processing that dispatches the code to the main thread.

An example in our sample app:
https://github.com/pjsip/pjproject/pull/2636/files#diff-da2adacd1ddac42831029da7d06450437dbc8a6abbee95214c5570de147aa0ddR101

**Review by trengginas — APPROVED** [review]

File: pjmedia/src/pjmedia/event.c (hunk 1 above)
Comment (nanangizz) [reply pjmedia/src/pjmedia/event.c:128]: ah okay, so `*next_sub` may be changed/updated by `unsubscribe()` while mutex is released.

**Comment by nanangizz** [comment]
> `pjsua_call_hangup()` is not supposed to be called from the main/UI thread. Even now (without this patch), it will cause deadlock with any video processing that dispatches the code to the main thread.
> 
> An example in our sample app:
> https://github.com/pjsip/pjproject/pull/2636/files#diff-da2adacd1ddac42831029da7d06450437dbc8a6abbee95214c5570de147aa0ddR101

okay, so this should confirm the urgency of updating `pjsua_call_hangup()`, right? the docs does not specify anything about that, and moreover, not sure if we should put the burden to the app.

**Comment by sauwming** [comment]
> okay, so this should confirm the urgency of updating `pjsua_call_hangup()`, right? the docs does not specify anything about that, and moreover, not sure if we should put the burden to the app.

Not necessarily. Because it's not just limited to `pjsua_call_hangup()`, any PJSIP API that potentially blocks/causes delay should not be put in the main thread. Example of APIs that will deadlock if called from the main thread are the ones trying to acquire vid conference's mutex, such as `pjsua_vid_conf_*()` APIs or video manipulation API such as `pjsua_call_set_vid_strm()`.

Even if it doesn't block, any delay while waiting for a lock, even for a fraction of a second, will be perceived as a fraction of second lag in video rendering/GUI update by the user. So that's why so far our recommendation is to call PJSIP API from another thread (a separate, dedicated thread is better), and for iOS, using dispatch mechanism to do this is not allowed due to compatibility issue with POSIX threads.

If we want to make it simpler for the user, I suppose we should create our own thread dispatching mechanism, i.e. `pj_dispatch()`. I imagine this will be somewhat similar to Endpoint's `pendingJobs`.
Another alternative is to remove our thread registration requirement, in order for PJSIP to be compatible with Apple's dispatch, so user can directly use Apple's dispatch feature. I'm not sure though whether Android/Kotlin has a similar feature.

**Comment by nanangizz** [comment]
> Not necessarily. Because it's not just limited to `pjsua_call_hangup()`, any PJSIP API that potentially blocks/causes delay should not be put in the main thread. Example of APIs that will deadlock if called from the main thread are the ones trying to acquire vid conference's mutex, such as `pjsua_vid_conf_*()` APIs or video manipulation API such as `pjsua_call_set_vid_strm()`.

Yes, agree, not limited to `pjsua_call_hangup()` actually.

> Even if it doesn't block, any delay while waiting for a lock, even for a fraction of a second, will be perceived as a fraction of second lag in video rendering/GUI update by the user. So that's why so far our recommendation is to call PJSIP API from another thread (a separate, dedicated thread is better), and for iOS, using dispatch mechanism to do this is not allowed due to compatibility issue with POSIX threads.
> 
> If we want to make it simpler for the user, I suppose we should create our own thread dispatching mechanism, i.e. `pj_dispatch()`. I imagine this will be somewhat similar to Endpoint's `pendingJobs`.
> Another alternative is to remove our thread registration requirement, in order for PJSIP to be compatible with Apple's dispatch, so user can directly use Apple's dispatch feature. I'm not sure though whether Android/Kotlin has a similar feature.

The concern about leaving it to app is mainly about its inconvenience, e.g: passing & maintaining function parameters between threads is not a simple task as some of them may be a complex data type that need extra care of its life time (memory allocated var or reference counted var). Also currently it may not be specified clearly in our docs/wiki.

I think we need to review & discuss this further, in the coming annual meeting perhaps.

**Comment by houhm** [comment]
hello,how did I do it at objective-c? when I  call " pjsua_schedule_timer2_dbg", it will throw the error with "Implicit declaration of function 'pjsua_schedule_timer2_dbg' is invalid in C99"

**Comment by sauwming** [comment]
You can try using `pjsua_schedule_timer2()` instead.
But it's more recommended to create your own thread and delegate the task to the thread.
