### PR TITLE
Fixed PJSUA2 API to get/set Opus config

### LINKED ISSUE #3934: The makefile for SWIG does not pass parameters for conditional compilation
### Describe the bug

Endpoint.hpp is used to compile pjsua2_wrap.cpp, but there is a condition there  
`#if defined(PJMEDIA_HAS_OPUS_CODEC) && (PJMEDIA_HAS_OPUS_CODEC!=0)`
And to build pjsua2_wrap.cpp which would contain methods `getCodecOpusConfig()` and `setCodecOpusConfig()` I had to edit the `pjproject-2.14.1/pjsip-apps/src/swig/python/Makefile`. I have shown it in green on the screenshot. Overall, it was too non-obvious. Could you please improve this process or mention somewhere in the instructions about this. Thanks!

image

### Steps to reproduce

Use these instructions: https://docs.pjsip.org/en/latest/pjsua2/building.html#building-python-swig-module

### PJSIP version

2.14

### Context

This affects the SWIG building for all high level languages (Java Python C#)

### Log, call stack, etc

```shell
(.pjproject-venv) romk@RG:~/pjproject-2.14.1/pjsip-apps/src/swig/python$ make
swig -I../../../../pjlib/include -I../../../../pjlib-util/include -I../../../../pjmedia/include -I../../../../pjsip/include -I../../../../pjnath/include -c++  -w312 -threads -DSWIG_NO_EXPORT_ITERATOR_METHODS -python -o pjsua2_wrap.cpp ../pjsua2.i
python3 setup.py build
```

### PR DESCRIPTION
**Pull request by sauwming**
To fix #3934.

Checking the macro `PJMEDIA_HAS_OPUS_CODEC` within the PJSUA2 API declaration will complicate the build process, such as for SWIG binding.
We should check the macro in the implementation instead.

### CODE REVIEW

File: pjsip/src/pjsua2/endpoint.cpp [hunk 1]
```diff
@@ -2515,9 +2517,10 @@ void Endpoint::setCodecOpusConfig(const CodecOpusConfig &opus_cfg)
 
    PJSUA2_CHECK_EXPR(pjmedia_codec_opus_set_default_param(&new_opus_cfg,
                                                           &param));
-}
-
+#else
+    PJ_UNUSED_ARG(opus_cfg);
 #endif
```
Comment (nanangizz) [inline pjsip/src/pjsua2/endpoint.cpp:2522]: What if it throws some exception (e.g: `PJ_ENOTSUP`) when Opus is not enabled? (also in `getCodecOpusConfig()`)

**Review by nanangizz — APPROVED** [review]
