### PR TITLE
Don't call SSL_shutdown() when receiving SSL_ERROR_SYSCALL or SSL_ERROR_SSL

### LINKED ISSUE #3576: Potentially improper use of SSL_shutdown() when receiving SSL_ERROR_SYSCALL or SSL_ERROR_SSL
### Describe the bug

In the man page for SSL_get_error, specifically with regards to SSL_ERROR_SYSCALL and SSL_ERROR_SSL, it states:

https://www.openssl.org/docs/man1.0.2/man3/SSL_get_error.html

>SSL_ERROR_SYSCALL
>Some non-recoverable, fatal I/O error occurred. The OpenSSL error queue may contain more information on the error. For >socket I/O on Unix systems, consult errno for details. If this error occurs then no further I/O operations should be performed >on the connection and SSL_shutdown() must not be called.
>
>SSL_ERROR_SSL
>A non-recoverable, fatal error in the SSL library occurred, usually a protocol error. The OpenSSL error queue contains more >information on the error. If this error occurs then no further I/O operations should be performed on the connection and >SSL_shutdown() must not be called.

It would appear that there's a CVE against openssl that caused this change in behavior:

https://forge.etsi.org/rep/cyber/103523_MSP/tlmsp/tlmsp-openssl/-/commit/ab874dfd3e22a7c6ea3d45bc352294546af5afff

In ssl_sock_ossl.c, if we receive either of these errors when performing an SSL_read(), it would appear that we need to ensure that ssl_reset_sock_state() does not call SSL_shutdown() when those errors are received to comply with this documented behavior.

### Steps to reproduce

Receive SSL_ERROR_SSL on TLS connection.

### PJSIP version

2.12.1+

### Context

n/a

### Log, call stack, etc

```shell
n/a
```

### PR DESCRIPTION
**Pull request by trengginas**
This is to fix #3576.
Before calling `SSL_shutdown()`, a check to SSL_ERROR_SYSCALL and SSL_ERROR_SSL is required.

### CODE REVIEW

File: pjlib/src/pj/ssl_sock_ossl.c [hunk 1]
```diff
@@ -1695,7 +1695,12 @@ static void ssl_destroy(pj_ssl_sock_t *ssock)
 /* Reset SSL socket state */
 static void ssl_reset_sock_state(pj_ssl_sock_t *ssock)
 {
-    ossl_sock_t *ossock = (ossl_sock_t *)ssock;
+    ssl_reset_sock_state_with_error(ssock, PJ_TRUE);
+}
+
+static void ssl_reset_sock_state_with_error(pj_ssl_sock_t* ssock, pj_bool_t check_error)
+{
+    ossl_sock_t* ossock = (ossl_sock_t*)ssock;
```
Comment (sauwming) [inline pjlib/src/pj/ssl_sock_ossl.c:1703]: Minor: our PointerAlignment is actually `Right`, i.e. see the initial code:
`ossl_sock_t *ossock = (ossl_sock_t *)ssock`

File: pjlib/src/pj/ssl_sock_ossl.c [hunk 2]
```diff
@@ -1706,12 +1711,21 @@ static void ssl_reset_sock_state(pj_ssl_sock_t *ssock)
      * Avoid calling SSL_shutdown() if handshake wasn't completed.
      * OpenSSL 1.0.2f complains if SSL_shutdown() is called during an
      * SSL handshake, while previous versions always return 0.
+     * Don't send notify when the last error is SSL_ERROR_SYSCALL or SSL_ERROR_SSL.
```
Comment (sauwming) [inline pjlib/src/pj/ssl_sock_ossl.c:1714]: Replace `send notify` with `call SSL_shutdown()`.

Yes, SSL_shutdown() will send notify, but it's only one of the steps.
`Note that SSL_shutdown() must not be called if a previous fatal error has occurred on a connection i.e. if SSL_get_error() has returned SSL_ERROR_SYSCALL or SSL_ERROR_SSL.

The shutdown procedure consists of two steps: sending of the close_notify shutdown alert, and reception of the peer's close_notify shutdown alert. The order of those two steps depends on the application.`
https://www.openssl.org/docs/manmaster/man3/SSL_shutdown.html

Also change the boolean below.

**Comment by creslin2877** [comment]
The only concern I have is that last_err might be set from an ssl_write context while ssl_read is being executed (due to concerns brought up in #3575).  I just pushed my patch up for it, so we'll probably have a merge conflict to deal with whenever your branch or mine goes in, but in any case, I think the locking in the fix for #3575 will make things a bit better.

**Comment by sauwming** [comment]
Since #3583 has been integrated, you can merge with the latest master to resolve the conflict.

**Review by creslin2877 — CHANGES_REQUESTED** [review]
As mentioned in my previous comment, we need to cover the case where we get an SSL_ERROR_SSL from the SSL_read() function too.

**Comment by sauwming** [comment]
> As mentioned in my previous comment, we need to cover the case where we get an SSL_ERROR_SSL from the SSL_read() function too.

Since, after merging, it now already uses the locking in `ssl_read()`, let us know if there are further modifications required.

**Comment by sauwming** [comment]
@creslin2877, let us know if there's any issue with the latest patch, so we can merge it for 2.13.1.

**Comment by sauwming** [comment]
I just realised that the addition of `ssl_reset_sock_state_with_error()` will break other SSL backends. Can we avoid modifying the internal API?

**Comment by creslin2877** [comment]
I think you've covered the case that triggered my concern.  Thanks!

**Review by sauwming — APPROVED** [review]

**Review by nanangizz — APPROVED** [review]
